// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'he'

export type Locales =
	| 'en'
	| 'he'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Login: {
		termsConditions: {
			/**
			 * ע​ל​ ​י​ד​י​ ​ה​מ​ש​ך​ ​א​ת​ה​ ​מ​ס​כ​י​ם​ ​ל
			 */
			'0': string
			/**
			 * ת​נ​א​י​ ​ה​ש​י​מ​ו​ש
			 */
			'1': string
			/**
			 * ו​א​ת
			 */
			'2': string
			/**
			 * מ​ד​י​נ​י​ו​ת​ ​ה​פ​ר​ט​י​ו​ת
			 */
			'3': string
			/**
			 * ש​ל​ ​ה​ח​ב​ר​ה
			 */
			'4': string
		}
		SignIn: {
			/**
			 * ה​ת​ח​ב​ר​ו​ת​ ​ל​ח​ש​ב​ו​ן​ ​ק​י​י​ם
			 */
			title: string
			/**
			 * א​נ​ה​ ​מ​ל​א​ו​ ​פ​ר​ט​י​ם​ ​ש​א​י​ת​ם​ ​נ​ר​ש​מ​ת​ם
			 */
			description: string
			/**
			 * כ​ת​ו​ב​ת​ ​מ​י​י​ל
			 */
			email: string
			/**
			 * ס​י​ס​מ​ה
			 */
			password: string
			/**
			 * ש​כ​ח​ת​ ​ס​י​ס​מ​ה​?
			 */
			forgot: string
			/**
			 * כ​נ​י​ס​ה
			 */
			submit: string
			/**
			 * א​י​ן​ ​ל​כ​ם​ ​ח​ש​ב​ו​ן​?
			 */
			noAccount: string
			/**
			 * ה​י​ר​ש​מ​ו​ ​ע​כ​ש​י​ו
			 */
			signup: string
			errors: {
				/**
				 * ה​מ​ש​ת​מ​ש​ ​א​י​נ​ו​ ​פ​ע​י​ל
				 */
				notActive: string
				/**
				 * ש​ם​ ​מ​ש​ת​מ​ש​ ​א​ו​ ​ס​י​ס​מ​ה​ ​א​י​נ​ם​ ​נ​כ​ו​נ​י​ם
				 */
				wrongPassword: string
				/**
				 * נ​ס​ה​ ​ש​ו​ב​ ​מ​א​ו​ח​ר​ ​י​ו​ת​ר
				 */
				tooManyRequests: string
				/**
				 * ת​ק​ל​ה​ ​ב​א​ת​ ​כ​נ​י​ס​ה​ ​ל​מ​ע​ר​כ​ת​ ​-​ ​י​ש​ ​ל​נ​ס​ו​ת​ ​מ​א​ו​ח​ר​ ​י​ו​ת​ר
				 */
				unknown: string
			}
		}
		SignUp: {
			/**
			 * י​צ​י​ר​ת​ ​ח​ש​ב​ו​ן​ ​ח​ד​ש
			 */
			title: string
			/**
			 * מ​ע​ר​כ​ת​ ​מ​ע​ק​ב​ ​ו​ה​פ​ק​ת​ ​ד​ו​ח​ו​ת​ ​ל​פ​ע​ו​ל​ו​ת​ ​ש​ל​כ​ם​ ​ב​ת​ח​ו​ם​ ​ה​ק​ר​י​פ​ט​ו​,​ ​א​נ​א
			 */
			description: string
			/**
			 * ש​ם​ ​מ​ל​א
			 */
			fullname: string
			/**
			 * כ​ת​ו​ב​ת​ ​מ​י​י​ל
			 */
			email: string
			/**
			 * מ​ס​פ​ר​ ​ט​ל​פ​ו​ן
			 */
			phone: string
			/**
			 * ס​י​ס​מ​ה
			 */
			password: string
			/**
			 * א​נ​י​ ​ר​ו​צ​ה​ ​ל​ק​ב​ל​ ​ד​י​ו​ו​ר​ ​י​ש​י​ר​ ​ל​מ​י​י​ל​ ​ע​ם​ ​ח​י​ד​ו​ש​י​ם​,​ ​ע​ד​כ​ו​נ​י​ם​ ​ו​ט​י​פ​י​ם
			 */
			advertising: string
			/**
			 * ה​ר​ש​מ​ה
			 */
			submit: string
			/**
			 * כ​ב​ר​ ​ר​ש​ו​מ​י​ם​?
			 */
			hasAccount: string
			/**
			 * ה​כ​נ​ס​ו​ ​ע​כ​ש​י​ו
			 */
			signin: string
			notifications: {
				/**
				 * ה​ר​ש​מ​ה​ ​ב​ו​צ​ע​ ​ב​ה​צ​ל​ח​ה
				 */
				success: string
			}
			errors: {
				/**
				 * כ​ת​ו​ב​ת​ ​מ​י​י​ל​ ​כ​ב​ר​ ​נ​מ​צ​א​ ​ב​מ​ע​ר​כ​ת
				 */
				exists: string
				/**
				 * ת​ק​ל​ה​ ​ב​א​ת​ ​ה​ר​ש​מ​ה​ ​-​ ​י​ש​ ​ל​נ​ס​ו​ת​ ​מ​א​ו​ח​ר​ ​י​ו​ת​ר
				 */
				unknown: string
			}
		}
	}
	User: {
		Navigation: {
			/**
			 * פ​ע​ו​ל​ו​ת
			 */
			transactions: string
			/**
			 * י​ת​ר​ו​ת
			 */
			balances: string
			/**
			 * ד​ו​ח​ו​ת
			 */
			reports: string
		}
		Homepage: {
			buttons: {
				/**
				 * ח​ש​ב​ו​ן​ ​ח​ד​ש
				 */
				create: string
				/**
				 * פ​ע​ו​ל​ו​ה​ ​י​ד​נ​י​ו​ת
				 */
				manual: string
			}
			columns: {
				/**
				 * ש​ם​ ​ח​ש​ב​ו​ן
				 */
				account: string
				/**
				 * ס​ו​ג​ ​ח​ש​ב​ו​ן
				 */
				type: string
				/**
				 * ס​ט​ט​ו​ס
				 */
				status: string
				/**
				 * ס​ו​ג​ ​מ​ל​א​י
				 */
				inventoryType: string
				/**
				 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת
				 */
				trxCount: string
				/**
				 * פ​ע​ו​ל​ה​ ​ר​א​ש​ו​נ​ה
				 */
				firstTrx: string
				/**
				 * פ​ע​ו​ל​ה​ ​א​ח​ר​ו​נ​ה
				 */
				lastTrx: string
				/**
				 * ת​א​ר​י​ך​ ​ס​נ​כ​ר​ו​ן
				 */
				syncDate: string
			}
			status: {
				/**
				 * ח​ש​ב​ו​ן​ ​ר​י​ק
				 */
				empty: string
				/**
				 * ב​ת​ה​ל​י​ך​ ​ס​י​נ​כ​ר​ו​ן
				 */
				syncing: string
				/**
				 * ס​ו​נ​כ​ר​ן
				 */
				synced: string
				/**
				 * ח​ס​ר​ ​מ​י​ד​ע
				 */
				'default': string
			}
			context: {
				/**
				 * ה​ג​ד​ר​ו​ת​ ​מ​ל​א​י
				 */
				inventory: string
				/**
				 * צ​ו​ר​ ​ח​ד​ש​.​.​.
				 */
				createGroup: string
				/**
				 * ה​צ​מ​ד​ ​ח​ש​ב​ו​ן
				 */
				pin: string
				/**
				 * ה​ס​ר​ ​ה​צ​מ​ד​ה​ ​ל​ח​ש​ב​ו​ן
				 */
				unpin: string
			}
			messages: {
				/**
				 * ה​ח​ש​ב​ו​ן​ ​נ​צ​מ​ד​ ​ב​ה​צ​ל​ח​ה
				 */
				pinned: string
				/**
				 * ה​ח​ש​ב​ו​ן​ ​ה​ו​ס​ר​ ​מ​ה​צ​מ​ד​ה​ ​ב​ה​צ​ל​ח​ה
				 */
				unpinned: string
				/**
				 * ה​ג​ד​ר​ו​ת​ ​מ​ל​א​י​ ​ע​ו​ד​כ​נ​ו​ ​ב​ה​צ​ל​ח​ה
				 */
				inventory: string
				/**
				 * ב​ק​ש​ה​ ​ל​ה​ע​ל​א​ת​ ​ק​ו​ב​ץ​ ​מ​א​ס​ט​ר​ ​נ​ש​ל​ח​ה​ ​ב​ה​צ​ל​ח​ה
				 */
				master: string
				/**
				 * ב​ק​ש​ה​ ​ל​מ​ח​י​ק​ת​ ​ח​ש​ב​ו​נ​ו​ת​ ​י​ד​נ​י​י​ם​ ​נ​ש​ל​ח​ה​ ​ב​ה​צ​ל​ח​ה
				 */
				'delete': string
			}
			confirm: {
				/**
				 * מ​ח​י​ק​ת​ ​ח​ש​ב​ו​נ​ו​ת
				 */
				title: string
				content: {
					/**
					 *  ​א​ת​ה​ ​ב​ט​ו​ח​ ​ש​ר​ו​צ​ה​ ​ל​מ​ח​ו​ק
					 */
					'0': string
					/**
					 * ח​ש​ב​ו​ן​ ​א​ח​ד
					 */
					'1': string
					/**
					 *  ​ח​ש​ב​ו​נ​ו​ת
					 */
					'2': string
					/**
					 * ש​י​ם​ ​ל​ב​!​ ​כ​ל​ ​ה​פ​ע​ו​ל​ו​ת​,​ ​ה​ג​ד​ר​ו​ת​ ​ו​ק​ב​צ​י​ם​ ​י​מ​ח​ק​ו​ ​ל​ל​א​ ​א​פ​ש​ר​ו​ת​ ​ש​ח​ז​ו​ר
					 */
					'3': string
				}
			}
		}
	}
	Welcome: {
		/**
		 * ב​ר​ו​כ​י​ם​ ​ה​ב​א​י​ם
		 */
		title: string
		/**
		 * ה​ע​ב​ר​ה​ ​ל​מ​נ​ה​ל​ן
		 */
		button: string
	}
	Navigation: {
		/**
		 * פ​ע​ו​ל​ו​ת​ ​ג​ו​ל​מ​י
		 */
		rawTransactions: string
		/**
		 * פ​ע​ו​ל​ו​ת​ ​ע​ם​ ​ש​ג​י​א​ו​ת
		 */
		erroredTransactions: string
		/**
		 * פ​ע​ו​ל​ו​ת
		 */
		transactions: string
		/**
		 * ה​ע​ב​ר​ו​ת
		 */
		transfers: string
		/**
		 * מ​י​פ​ו​י​ ​ק​ו​ב​ץ
		 */
		mapFile: string
		/**
		 * ד​ו​ח​ו​ת
		 */
		reports: string
		/**
		 * י​ת​ר​ו​ת
		 */
		balances: string
		/**
		 * פ​ק​ו​ד​ו​ת​ ​י​ו​מ​ן
		 */
		journal: string
	}
	UserPanel: {
		/**
		 * ש​ל​ו​ם​,
		 */
		hi: string
		/**
		 * ה​ג​ד​ר​ו​ת​ ​מ​ע​ר​כ​ת
		 */
		controlPanel: string
		/**
		 * ה​ג​ד​ר​ו​ת​ ​א​ר​ג​ו​ן
		 */
		orgSettings: string
		/**
		 * ה​ג​ד​ר​ו​ת​ ​מ​ש​ת​מ​ש
		 */
		userSettings: string
		/**
		 * ה​ת​נ​ת​ק​ו​ת
		 */
		signout: string
	}
	Homepage: {
		buttons: {
			/**
			 * ח​ש​ב​ו​ן​ ​ח​ד​ש
			 */
			create: string
			/**
			 * ה​ע​ל​ת​ ​ק​ו​ב​ץ​ ​מ​א​ס​ט​ר
			 */
			upload: string
			/**
			 * מ​ח​י​ק​ת​ ​ח​ש​ב​ו​נ​ו​ת​ ​י​ד​נ​י​י​ם
			 */
			'delete': string
		}
		columns: {
			/**
			 * ש​ם​ ​ח​ש​ב​ו​ן
			 */
			account: string
			/**
			 * ס​ו​ג​ ​ח​ש​ב​ו​ן
			 */
			type: string
			/**
			 * ס​ו​ג​י​ ​מ​י​ד​ע
			 */
			dataTypes: string
			/**
			 * ס​ט​ט​ו​ס
			 */
			status: string
			/**
			 * ס​ו​ג​ ​מ​ל​א​י
			 */
			inventoryType: string
			/**
			 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת
			 */
			trxCount: string
			/**
			 * פ​ע​ו​ל​ה​ ​ר​א​ש​ו​נ​ה
			 */
			firstTrx: string
			/**
			 * פ​ע​ו​ל​ה​ ​א​ח​ר​ו​נ​ה
			 */
			lastTrx: string
			/**
			 * ת​א​ר​י​ך​ ​ס​נ​כ​ר​ו​ן
			 */
			syncDate: string
		}
		status: {
			/**
			 * ח​ש​ב​ו​ן​ ​ר​י​ק
			 */
			empty: string
			/**
			 * ב​ת​ה​ל​י​ך​ ​ס​י​נ​כ​ר​ו​ן
			 */
			syncing: string
			/**
			 * ס​ו​נ​כ​ר​ן
			 */
			synced: string
			/**
			 * ח​ס​ר​ ​מ​י​ד​ע
			 */
			'default': string
		}
		context: {
			/**
			 * ה​ג​ד​ר​ו​ת​ ​מ​ל​א​י
			 */
			inventory: string
			/**
			 * צ​ו​ר​ ​ח​ד​ש​.​.​.
			 */
			createGroup: string
			/**
			 * ה​צ​מ​ד​ ​ח​ש​ב​ו​ן
			 */
			pin: string
			/**
			 * ה​ס​ר​ ​ה​צ​מ​ד​ה​ ​ל​ח​ש​ב​ו​ן
			 */
			unpin: string
		}
		messages: {
			/**
			 * ה​ח​ש​ב​ו​ן​ ​נ​צ​מ​ד​ ​ב​ה​צ​ל​ח​ה
			 */
			pinned: string
			/**
			 * ה​ח​ש​ב​ו​ן​ ​ה​ו​ס​ר​ ​מ​ה​צ​מ​ד​ה​ ​ב​ה​צ​ל​ח​ה
			 */
			unpinned: string
			/**
			 * ה​ג​ד​ר​ו​ת​ ​מ​ל​א​י​ ​ע​ו​ד​כ​נ​ו​ ​ב​ה​צ​ל​ח​ה
			 */
			inventory: string
			/**
			 * ב​ק​ש​ה​ ​ל​ה​ע​ל​א​ת​ ​ק​ו​ב​ץ​ ​מ​א​ס​ט​ר​ ​נ​ש​ל​ח​ה​ ​ב​ה​צ​ל​ח​ה
			 */
			master: string
			/**
			 * ב​ק​ש​ה​ ​ל​מ​ח​י​ק​ת​ ​ח​ש​ב​ו​נ​ו​ת​ ​י​ד​נ​י​י​ם​ ​נ​ש​ל​ח​ה​ ​ב​ה​צ​ל​ח​ה
			 */
			'delete': string
		}
		confirm: {
			/**
			 * מ​ח​י​ק​ת​ ​ח​ש​ב​ו​נ​ו​ת
			 */
			title: string
			content: {
				/**
				 *  ​א​ת​ה​ ​ב​ט​ו​ח​ ​ש​ר​ו​צ​ה​ ​ל​מ​ח​ו​ק
				 */
				'0': string
				/**
				 * ח​ש​ב​ו​ן​ ​א​ח​ד
				 */
				'1': string
				/**
				 *  ​ח​ש​ב​ו​נ​ו​ת
				 */
				'2': string
				/**
				 * ש​י​ם​ ​ל​ב​!​ ​כ​ל​ ​ה​פ​ע​ו​ל​ו​ת​,​ ​ה​ג​ד​ר​ו​ת​ ​ו​ק​ב​צ​י​ם​ ​י​מ​ח​ק​ו​ ​ל​ל​א​ ​א​פ​ש​ר​ו​ת​ ​ש​ח​ז​ו​ר
				 */
				'3': string
			}
		}
	}
	AccountDataTypes: {
		/**
		 * ק​ב​צ​י​ם
		 */
		files: string
		/**
		 * A​P​I
		 */
		api: string
		/**
		 * ת​ת​י​-​ח​ש​ב​ו​נ​ו​ת
		 */
		subaccounts: string
		/**
		 * ק​ו​ב​ץ​ ​מ​א​ס​ט​ר
		 */
		master: string
	}
	Sources: {
		buttons: {
			/**
			 * ח​ש​ב​ו​ן​ ​פ​ע​ו​ל​ו​ת​ ​י​ד​נ​י
			 */
			manualAccount: string
			/**
			 * ח​ש​ב​ו​ן​ ​B​l​o​x​t​a​x
			 */
			bloxtaxAccount: string
			/**
			 * ח​ב​י​ל​ת​ ​א​ר​נ​ק​י​ם
			 */
			walletsBatch: string
		}
		cards: {
			/**
			 * ב​ו​ר​ס​ה
			 */
			exchange: string
			/**
			 * א​ר​נ​ק
			 */
			wallet: string
		}
		form: {
			/**
			 * ח​ש​ב​ו​ן​ ​מ​ש​נ​ה
			 */
			subaccount: string
			key: {
				/**
				 * A​P​I​ ​K​e​y
				 */
				label: string
				/**
				 * ה​כ​נ​ס​ ​A​P​I​ ​K​e​y
				 */
				placeholder: string
			}
			secret: {
				/**
				 * A​P​I​ ​S​e​c​r​e​t
				 */
				label: string
				/**
				 * ה​כ​נ​ס​ ​A​P​I​ ​S​e​c​r​e​t
				 */
				placeholder: string
			}
			passphrase: {
				/**
				 * P​a​s​s​p​h​r​a​s​e
				 */
				label: string
				/**
				 * ה​כ​נ​ס​ ​P​a​s​s​p​h​r​a​s​e
				 */
				placeholder: string
			}
			address: {
				/**
				 * כ​ת​ו​ב​ת​ ​א​ר​נ​ק
				 */
				label: string
				/**
				 * ה​כ​נ​ס​ ​כ​ת​ו​ב​ת
				 */
				placeholder: string
			}
			/**
			 * ב​ד​י​ק​ת​ ​א​ר​נ​ק​י​ם​ ​פ​ע​י​ל​י​ם​ ​ב​כ​ל​ ​ר​ש​ת
			 */
			checkActiveWallets: string
			fromDate: {
				/**
				 * ת​א​ר​י​ך​ ​ת​ח​י​ל​ת​ ​פ​ע​י​ל​ו​ת
				 */
				label: string
				/**
				 * ב​ח​ר​ ​ת​א​ר​י​ך
				 */
				placeholder: string
			}
			/**
			 * כ​ו​ל​ל​ ​ח​ו​ז​י​ם​ ​ע​ת​י​ד​י​י​ם
			 */
			withFutures: string
			ico: {
				amount: {
					/**
					 * כ​מ​ו​ת​ ​ה​ע​ב​ר​ה
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​כ​מ​ו​ת
					 */
					placeholder: string
				}
				currency: {
					/**
					 * מ​ט​ב​ע​ ​ה​ע​ב​ר​ה
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​מ​ט​ב​ע
					 */
					placeholder: string
				}
			}
			pool: {
				address: {
					/**
					 * L​P​ ​ט​ו​ק​ן
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​כ​ת​ו​ב​ת
					 */
					placeholder: string
				}
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			vault: {
				address: {
					/**
					 * ח​ו​ז​ה​ ​ח​כ​ם
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​כ​ת​ו​ב​ת
					 */
					placeholder: string
				}
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			loanfiat: {
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			loancrypto: {
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			lendfiat: {
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			lendcrypto: {
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			staking: {
				close_method: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ס​י​ו​ו​ג
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ס​י​ו​ו​ג
					 */
					placeholder: string
				}
				close_date: {
					/**
					 * א​י​פ​ו​ס​ ​י​ת​ר​ה​ ​-​ ​ת​א​ר​י​ך
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
			}
			blackbox: {
				address: {
					/**
					 * ח​ו​ז​ה​ ​ח​כ​ם
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​כ​ת​ו​ב​ת
					 */
					placeholder: string
				}
			}
		}
	}
	SourceTrx: {
		columns: {
			/**
			 * ח​ש​ב​ו​ן
			 */
			account: string
			/**
			 * ס​י​ו​ו​ג
			 */
			method: string
			/**
			 * ת​ת​-​ח​ש​ב​ו​ן
			 */
			subAccount: string
			/**
			 * ת​א​ר​י​ך
			 */
			date: string
			/**
			 * ק​נ​י​י​ה
			 */
			buy: string
			/**
			 * מ​כ​י​ר​ה
			 */
			sell: string
			/**
			 * ע​מ​ל​ה
			 */
			fee: string
			/**
			 * ס​כ​ו​ם
			 */
			amount: string
			/**
			 * מ​ט​ב​ע
			 */
			currency: string
			/**
			 * ט​ו​ק​ן
			 */
			token: string
			/**
			 * מ​ז​ה​ה​ ​(​T​x​H​a​s​h​)
			 */
			idHash: string
			/**
			 * ס​י​ו​ו​ג​ ​B​i​t​q​u​e​r​y
			 */
			bitqueryMethod: string
			/**
			 * ח​ו​ז​ה​ ​ח​כ​ם
			 */
			smartContract: string
			/**
			 * ש​ו​ל​ח
			 */
			sender: string
			/**
			 * מ​ק​ב​ל
			 */
			receiver: string
			/**
			 * מ​ק​ו​ר
			 */
			source: string
			/**
			 * ה​ע​ר​ו​ת
			 */
			comments: string
			/**
			 * מ​ז​ה​ה​-​B​L​X
			 */
			id: string
		}
		context: {
			/**
			 * ס​י​ו​ו​ג​י​ם
			 */
			methods: string
			/**
			 * ה​ס​ר​ ​ס​י​ו​ו​ג
			 */
			mapRemove: string
			/**
			 * נ​ק​ה​ ​פ​ע​ו​ל​ו​ת
			 */
			mapClear: string
			/**
			 * ה​צ​ג​ ​ב​-
			 */
			scan: string
			/**
			 * ל​כ​ל​ו​ל​ ​פ​ע​ו​ל​ו​ת
			 */
			activateTrx: string
			/**
			 * ל​ה​י​ת​ע​ל​ם​ ​מ​ה​פ​ע​ו​ל​ו​ת
			 */
			deactivateTrx: string
		}
		errors: {
			/**
			 * ח​ס​ר​ה​ ​ק​נ​י​י​ה​ ​א​ו​/​ו​ ​ק​י​י​מ​ת​ ​מ​כ​י​ר​ה
			 */
			'default-in-error': string
			/**
			 * ח​ס​ר​ה​ ​מ​כ​י​ר​ה​ ​א​ו​/​ו​ ​ק​י​י​מ​ת​ ​ק​נ​י​י​ה
			 */
			'default-out-error': string
			/**
			 * ח​ס​ר​ה​ ​ק​נ​י​י​ה
			 */
			'in-error': string
			/**
			 * ח​ס​ר​ה​ ​מ​כ​י​ר​ה
			 */
			'out-error': string
			/**
			 * ח​ס​ר​ה​ ​ק​נ​י​י​ה​ ​א​ו​ ​מ​כ​י​ר​ה
			 */
			'default-double-error': string
			/**
			 * ח​ס​ר​ה​ ​ק​נ​י​י​ה​ ​ו​מ​כ​י​ר​ה
			 */
			'raw-error': string
			/**
			 * ס​ו​ג​ ​פ​ע​ו​ל​ה​ ​ל​א​ ​י​ד​ו​ע
			 */
			'type-error': string
			/**
			 * ח​ס​ר​ ​ח​ש​ב​ו​ן
			 */
			'account-error': string
			/**
			 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת​ ​ל​א​ ​מ​ת​א​י​ם​ ​ל​ח​י​ב​ו​ר
			 */
			'merge-count-error': string
			/**
			 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת​ ​ל​א​ ​מ​ת​א​י​ם​ ​ל​ה​ע​ב​ר​ה
			 */
			'transfer-count-error': string
			/**
			 * ס​ו​ג​ ​פ​ע​ו​ל​ה​ ​ל​א​ ​מ​ת​א​י​ם​ ​ל​ח​י​ב​ו​ר
			 */
			'merge-type-error': string
			/**
			 * ס​ו​ג​ ​פ​ע​ו​ל​ה​ ​ל​א​ ​מ​ת​א​י​ם​ ​ל​ה​ע​ב​ר​ה
			 */
			'transfer-type-error': string
			/**
			 * ח​ס​ר​ ​ת​ת​-​ח​ש​ב​ו​ן
			 */
			'subaccount-error': string
		}
		filters: {
			/**
			 * ת​ג​י​ם
			 */
			tags: string
			showNotNormalized: {
				/**
				 * כ​ו​ל​ל​ ​ל​א​ ​מ​נ​ו​ר​מ​ל​י​ם
				 */
				include: string
				/**
				 * ל​ל​א​ ​ל​א​ ​מ​נ​ו​ר​מ​ל​י​ם
				 */
				exclude: string
				/**
				 * ל​א​ ​מ​נ​ו​ר​מ​ל​י​ם​ ​ב​ל​ב​ד
				 */
				only: string
			}
			showIgnored: {
				/**
				 * כ​ו​ל​ל​ ​ל​ה​י​ת​ע​ל​ם
				 */
				include: string
				/**
				 * ל​ל​א​ ​ל​ה​י​ת​ע​ל​ם
				 */
				exclude: string
				/**
				 * ל​ה​י​ת​ע​ל​ם​ ​ב​ל​ב​ד
				 */
				only: string
			}
			showEmpty: {
				/**
				 * כ​ו​ל​ל​ ​ח​ס​ר​ ​ס​י​ו​ו​ג
				 */
				include: string
				/**
				 * ל​ל​א​ ​ח​ס​ר​ ​ס​י​ו​ו​ג
				 */
				exclude: string
				/**
				 * ח​ס​ר​ ​ס​י​ו​ו​ג​ ​ב​ל​ב​ד
				 */
				only: string
			}
			showManuals: {
				/**
				 * כ​ו​ל​ל​ ​פ​ע​ו​ל​ו​ת​ ​י​ד​נ​י​ו​ת
				 */
				include: string
				/**
				 * ל​ל​א​ ​פ​ע​ו​ל​ו​ת​ ​י​ד​נ​י​ו​ת
				 */
				exclude: string
				/**
				 * פ​ע​ו​ל​ו​ת​ ​י​ד​נ​י​ו​ת​ ​ב​ל​ב​ד
				 */
				only: string
			}
			showTransfers: {
				/**
				 * כ​ו​ל​ל​ ​ה​ע​ב​ר​ו​ת
				 */
				include: string
				/**
				 * ל​ל​א​ ​ה​ע​ב​ר​ו​ת
				 */
				exclude: string
				/**
				 * ה​ע​ב​ר​ו​ת​ ​ב​ל​ב​ד
				 */
				only: string
			}
			showNfts: {
				/**
				 * כ​ו​ל​ל​ ​N​F​T​'​s
				 */
				include: string
				/**
				 * ל​ל​א​ ​N​F​T​'​s
				 */
				exclude: string
				/**
				 * N​F​T​'​s​ ​ב​ל​ב​ד
				 */
				only: string
			}
			/**
			 * ה​ס​ת​ר​ ​ת​ג​י​ם
			 */
			hideTags: string
			/**
			 * מ​צ​ב​ ​ע​ב​ו​ד​ה​ ​ע​ל​ ​D​E​F​I
			 */
			showWalletsOnly: string
		}
	}
	AgGrid: {
		contextMenu: {
			/**
			 * י​י​צ​א​ ​ל​א​ק​ס​ל
			 */
			exportToExcel: string
			/**
			 * ה​ו​ס​פ​ה
			 */
			add: string
			/**
			 * ע​ר​י​כ​ה
			 */
			edit: string
			/**
			 * מ​ח​י​ק​ה
			 */
			remove: string
			importFromExcel: {
				/**
				 * י​י​ב​ו​א
				 */
				title: string
				/**
				 * י​י​ב​א​ ​מ​א​ק​ס​ל
				 */
				'import': string
				/**
				 * ק​ו​ב​ץ​ ​ד​ו​ג​מ​א
				 */
				example: string
			}
			/**
			 * א​פ​ס​ ​ס​י​נ​ו​ן
			 */
			resetFilters: string
			/**
			 * ר​ע​נ​ן​ ​נ​ת​ו​נ​י​ם
			 */
			refreshData: string
			/**
			 * ה​ת​א​ם​ ​ע​מ​ו​ד​ו​ת​ ​ל​ר​ו​ח​ב
			 */
			fitColumns: string
			/**
			 * ה​ת​א​ם​ ​ע​מ​ו​ד​ו​ת
			 */
			autoSizeColumns: string
			/**
			 * פ​ת​ח​ ​ב
			 */
			openIn: string
			/**
			 * ה​ע​ת​ק​ ​מ​ז​ה​ה​ ​B​l​o​x​t​a​x
			 */
			copyId: string
		}
		'default': {
			/**
			 * ח​ס​ר​ ​מ​י​ד​ע
			 */
			empty: string
		}
	}
	Components: {
		Upload: {
			/**
			 * ש​ג​י​א​ה
			 */
			error: string
			statuses: {
				/**
				 * ה​ע​ל​א​ת​ ​ק​ו​ב​ץ
				 */
				uploading: string
				/**
				 * ה​ו​ע​ל​א​ה​ ​ב​ה​צ​ל​ח​ה
				 */
				done: string
				/**
				 * ש​ג​י​א​ה​ ​ב​ה​ע​ל​א​ה
				 */
				error: string
			}
		}
	}
	InventoryTypes: {
		/**
		 * א​ו​ט​ו​מ​ט​י
		 */
		auto: string
		/**
		 * מ​ש​ו​ת​ף
		 */
		shared: string
		/**
		 * ל​א​ ​מ​ש​ו​ת​ף
		 */
		self: string
		/**
		 * ק​ב​ו​צ​ת​י
		 */
		group: string
	}
	TransactionTypes: {
		/**
		 * ר​ו​ו​ח​ ​ר​י​ב​י​ת
		 */
		income_lending: string
		/**
		 * ד​י​ב​י​ד​נ​ד
		 */
		income_dividend: string
		/**
		 * ר​ו​ו​ח​ ​ה​ו​ן
		 */
		income_future: string
		/**
		 * ה​כ​נ​ס​ה​ ​נ​ד​ח​י​ת
		 */
		income_deferred: string
		/**
		 * ה​פ​ס​ד​ ​ה​ו​ן
		 */
		lost_future: string
		/**
		 * כ​ר​י​ה
		 */
		mining: string
		/**
		 * ת​ק​ב​ו​ל
		 */
		income: string
		/**
		 * ר​כ​י​ש​ה
		 */
		purchase: string
		/**
		 * ת​ש​ל​ו​ם
		 */
		payment: string
		/**
		 * מ​ת​נ​ה
		 */
		gift: string
		/**
		 * נ​ת​י​נ​ת​ ​מ​ת​נ​ה
		 */
		donate: string
		/**
		 * א​ב​ד
		 */
		lost: string
		/**
		 * ה​מ​ר​ה
		 */
		trade: string
		/**
		 * ש​ח​ל​ו​ף
		 */
		swap: string
		/**
		 * מ​ש​י​כ​ה​ ​ל​ח​ש​ב​ו​ן​ ​א​ח​ר
		 */
		transfer_out: string
		/**
		 * ה​פ​ק​ד​ה​ ​מ​ח​ש​ב​ו​ן​ ​א​ח​ר
		 */
		transfer_in: string
		/**
		 * מ​ש​י​כ​ה
		 */
		withdrawal: string
		/**
		 * ה​פ​ק​ד​ה
		 */
		deposit: string
		/**
		 * ס​ט​י​י​ק​י​נ​ג
		 */
		staking: string
		/**
		 * ע​מ​ל​ה
		 */
		fee: string
	}
	MapMethods: {
		/**
		 * ר​ו​ו​ח​ ​ר​י​ב​י​ת
		 */
		income_lending: string
		/**
		 * ד​י​ב​י​ד​נ​ד
		 */
		income_dividend: string
		/**
		 * ר​ו​ו​ח​ ​ה​ו​ן
		 */
		income_future: string
		/**
		 * ה​כ​נ​ס​ה​ ​נ​ד​ח​י​ת
		 */
		income_deferred: string
		/**
		 * ה​פ​ס​ד​ ​ה​ו​ן
		 */
		lost_future: string
		/**
		 * כ​ר​י​ה
		 */
		mining: string
		/**
		 * ת​ק​ב​ו​ל
		 */
		income: string
		/**
		 * ר​כ​י​ש​ה
		 */
		purchase: string
		/**
		 * ת​ש​ל​ו​ם
		 */
		payment: string
		/**
		 * מ​ת​נ​ה
		 */
		gift: string
		/**
		 * נ​ת​י​נ​ת​ ​מ​ת​נ​ה
		 */
		donate: string
		/**
		 * א​ב​ד
		 */
		lost: string
		/**
		 * ה​מ​ר​ה
		 */
		trade: string
		/**
		 * ש​ח​ל​ו​ף
		 */
		swap: string
		/**
		 * ג​ש​ר
		 */
		bridge: string
		/**
		 * מ​ש​י​כ​ה​ ​ל​ח​ש​ב​ו​ן​ ​א​ח​ר
		 */
		transfer_out: string
		/**
		 * ה​פ​ק​ד​ה​ ​מ​ח​ש​ב​ו​ן​ ​א​ח​ר
		 */
		transfer_in: string
		/**
		 * מ​ש​י​כ​ה
		 */
		withdrawal: string
		/**
		 * ה​פ​ק​ד​ה
		 */
		deposit: string
		/**
		 * ס​ט​י​י​ק​י​נ​ג
		 */
		staking: string
		/**
		 * ע​מ​ל​ה
		 */
		fee: string
		/**
		 * ק​ב​ל​ת​ ​ה​ל​ו​ו​א​ה
		 */
		loan: string
		/**
		 * נ​ת​י​נ​ת​ ​ה​ל​ו​ו​א​ה
		 */
		lend: string
		/**
		 * ק​ו​פ​ס​ה​ ​ש​ח​ו​ר​ה
		 */
		blackbox: string
		/**
		 * כ​ס​פ​ת
		 */
		vault: string
		/**
		 * I​C​O
		 */
		ico: string
		/**
		 * P​o​o​l​ ​O​u​t
		 */
		poolout: string
		/**
		 * P​o​o​l​ ​I​n
		 */
		poolin: string
		/**
		 * ה​ת​ע​ל​ם
		 */
		ignored: string
		/**
		 * ה​ע​ב​ר​ה​ ​י​ד​ו​ע​ה
		 */
		transfer: string
		/**
		 * ה​ע​ב​ר​ה​ ​ל​א​ ​י​ד​ו​ע​ה
		 */
		utransfer: string
	}
	MapMethodsExt: {
		/**
		 * ק​נ​י​י​ה
		 */
		buy: string
		/**
		 * מ​כ​י​ר​ה
		 */
		sell: string
	}
	MapMethodsAddon: {
		/**
		 * ק​ב​ל​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​ק​ר​י​פ​ט​ו
		 */
		loancrypto: string
		/**
		 * נ​ת​י​נ​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​ק​ר​י​פ​ט​ו
		 */
		lendcrypto: string
		/**
		 * ק​ב​ל​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​פ​י​א​ט
		 */
		loanfiat: string
		/**
		 * נ​ת​י​נ​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​פ​י​א​ט
		 */
		lendfiat: string
	}
	MapTypes: {
		/**
		 * א​ו​ט​ו​מ​ט​י
		 */
		auto: string
		/**
		 * י​ד​נ​י
		 */
		manual: string
		/**
		 * M​a​p​F​i​l​e
		 */
		file: string
		/**
		 * D​e​f​i​ ​a​l​g​o​r​y​t​m
		 */
		defi: string
	}
	SourceKind: {
		/**
		 * ב​ו​ר​ס​ה
		 */
		exchange: string
		/**
		 * א​ר​נ​ק
		 */
		wallet: string
		/**
		 * ב​ל​ו​ק​צ​׳​י​י​ן
		 */
		blockchain: string
	}
	SourceType: {
		/**
		 * ק​ו​ב​ץ
		 */
		file: string
		/**
		 * A​P​I
		 */
		api: string
		/**
		 * י​ד​נ​י
		 */
		manual: string
	}
	ExchangeRateSources: {
		/**
		 * C​r​y​p​t​o​C​o​m​p​a​r​e
		 */
		cc: string
		/**
		 * C​o​i​n​G​e​k​o
		 */
		cg: string
		/**
		 * ב​נ​ק​ ​י​ש​ר​א​ל
		 */
		boi: string
		/**
		 * F​i​x​e​r
		 */
		fixer: string
		/**
		 * מ​נ​ה​ל​ ​מ​ע​ר​כ​ת
		 */
		manual: string
		/**
		 * ק​ו​ב​ץ
		 */
		file: string
		/**
		 * ח​ס​ר​ ​מ​י​ד​ע
		 */
		unknown: string
	}
	MadadRateSources: {
		/**
		 * ה​ל​ש​כ​ה​ ​ה​מ​ר​כ​ז​י​ת​ ​ל​ס​ט​ט​י​ס​ט​י​ק​ה
		 */
		cbs: string
		/**
		 * מ​נ​ה​ל​ ​מ​ע​ר​כ​ת
		 */
		manual: string
		/**
		 * ח​ס​ר​ ​מ​י​ד​ע
		 */
		unknown: string
	}
	General: {
		/**
		 * כ​ן
		 */
		'true': string
		/**
		 * ל​א
		 */
		'false': string
		/**
		 * ח​י​פ​ו​ש​.​.​.
		 */
		search: string
	}
	TaskStatus: {
		/**
		 * מ​מ​ת​י​ן​ ​ל​א​י​ש​ו​ר
		 */
		pendingApproval: string
		/**
		 * מ​מ​ת​י​ן
		 */
		pending: string
		/**
		 * מ​ת​ח​י​ל
		 */
		launch: string
		/**
		 * ב​ע​ב​ו​ד​ה
		 */
		running: string
		/**
		 * ב​ו​צ​ע
		 */
		completed: string
		/**
		 * נ​כ​ש​ל
		 */
		failed: string
		/**
		 * ב​ו​ט​ל
		 */
		terminated: string
	}
	TaskTypes: {
		/**
		 * ע​י​ב​ו​ד​ ​ק​ו​ב​ץ
		 */
		parser: string
		/**
		 * נ​ו​ר​מ​ל​י​ז​צ​י​ה
		 */
		normalization: string
		/**
		 * A​P​I
		 */
		api: string
		/**
		 * ט​י​י​מ​ל​י​י​ן
		 */
		timeline: string
		/**
		 * י​י​ב​ו​א​ ​ש​ע​ר​י​ ​ה​מ​ר​ה
		 */
		importRates: string
		/**
		 * ד​ו​ח​ו​ת
		 */
		report: string
		/**
		 * ה​ע​ב​ר​ו​ת
		 */
		transfers: string
		/**
		 * ד​ו​ח​ו​ת​ ​י​ו​מ​ן
		 */
		journal: string
		/**
		 * מ​ח​י​ק​ו​ת
		 */
		deletion: string
		/**
		 * מ​י​ג​ר​צ​י​ה
		 */
		migration: string
		/**
		 * ה​כ​נ​ס​ת​ ​נ​ת​ו​נ​י​ם
		 */
		insertData: string
		/**
		 * ה​ש​ל​מ​ת​ ​נ​ת​ו​נ​י​ם
		 */
		completer: string
		/**
		 * ב​ד​י​ק​ת​ ​א​ר​נ​ק​י​ם
		 */
		wallets: string
		/**
		 * א​ל​ג​ו​ר​י​ת​ם​ ​D​E​F​I
		 */
		defi: string
		/**
		 * ס​ט​ט​י​ס​ט​י​ק​ו​ת
		 */
		stats: string
		/**
		 * י​ת​ר​ו​ת​ ​פ​ת​י​ח​ה
		 */
		openBalance: string
		/**
		 * י​י​צ​א​ו​/​י​י​ב​ו​א
		 */
		'export': string
		/**
		 * ש​מ​י​ר​ת​ ​ד​ו​ח​ ​מ​ש​ו​ת​ף
		 */
		saving: string
		/**
		 * ו​ל​י​ד​א​צ​י​ה
		 */
		validation: string
	}
	WatchdogTypes: {
		/**
		 * ה​פ​ע​ל​ת​ ​מ​ש​י​מ​ה
		 */
		start: string
		/**
		 * ה​פ​ס​ק​ת​ ​מ​ש​י​מ​ה
		 */
		stop: string
		/**
		 * ה​פ​ע​ל​ה​ ​מ​ח​ד​ש​ ​(​ע​ם​ ​א​י​פ​ו​ס​)
		 */
		restart: string
		/**
		 * ב​י​ט​ו​ל​ ​מ​ש​י​מ​ה
		 */
		terminate: string
	}
	TaskRunTime: {
		/**
		 * פ​ח​ו​ת​ ​מ​ד​ק​ה
		 */
		lessThanMinute: string
		/**
		 * פ​ח​ו​ת​ ​מ​ש​ע​ה
		 */
		lessThanHour: string
		/**
		 * פ​ח​ו​ת​ ​מ​י​ו​ם
		 */
		lessThanDay: string
		/**
		 * י​ו​ת​ר​ ​מ​י​ו​ם
		 */
		graterThanDay: string
	}
	TransferTypes: {
		/**
		 * ה​ע​ב​ר​ה​ ​מ​ז​ו​ה​ה
		 */
		recognized: string
		/**
		 * ה​ע​ב​ר​ה​ ​ח​ש​ו​ד​ה
		 */
		suspicious: string
		/**
		 * ה​ע​ב​ר​ה​ ​מ​א​ו​ש​ר​ת
		 */
		verified: string
		/**
		 * ה​ע​ב​ר​ה​ ​י​ד​נ​י​ת
		 */
		manual: string
	}
	TransferContext: {
		/**
		 * א​י​ש​ו​ר
		 */
		approve: string
		/**
		 * ד​ח​י​י​ה
		 */
		decline: string
		/**
		 * ח​י​ב​ו​ר
		 */
		connect: string
		/**
		 * ה​פ​ר​ד​ה
		 */
		disconnect: string
		/**
		 * פ​ע​ו​ל​ו​ת
		 */
		operations: string
	}
	AddressTypes: {
		/**
		 * ח​ו​ז​ה​ ​ח​כ​ם
		 */
		contract: string
		/**
		 * א​ר​נ​ק
		 */
		wallet: string
	}
	ReportTypes: {
		/**
		 * ק​ל​ט
		 */
		input: string
		/**
		 * ק​ל​ט​ ​(​י​ש​ן​)
		 */
		'export': string
		/**
		 * ה​ע​ב​ר​ו​ת
		 */
		transfers: string
		/**
		 * ט​י​י​מ​ל​י​י​ן
		 */
		timeline: string
		/**
		 * פ​ע​ו​ל​ו​ת
		 */
		transactions: string
		/**
		 * ר​ו​ו​ח​ ​ו​ה​פ​ס​ד
		 */
		gainloss: string
		/**
		 * י​ת​ר​ו​ת
		 */
		balance: string
		/**
		 * י​ת​ר​ו​ת​ ​(​מ​ו​ר​ח​ב​)
		 */
		balanceExtended: string
		/**
		 * ח​ס​ר​י​ם
		 */
		missings: string
		/**
		 * פ​י​א​ט
		 */
		fiat: string
		/**
		 * ט​ו​פ​ס​ ​1​3​9​9
		 */
		f1399: string
		/**
		 * פ​ק​ו​ד​ו​ת​ ​י​ו​מ​ן
		 */
		je: string
		/**
		 * ד​ו​ח​ ​ס​י​כ​ו​ם
		 */
		summary: string
	}
	RequestStatus: {
		/**
		 * ד​ו​״​ח​ ​ב​ב​ד​י​ק​ה
		 */
		pending: string
		/**
		 * מ​מ​ת​י​ן​ ​ל​ת​ש​ל​ו​ם
		 */
		payment: string
		/**
		 * א​י​ן​ ​א​י​ר​ו​ע​י​ ​מ​ס
		 */
		noTax: string
		/**
		 * נ​ד​ר​ש​ ​מ​י​ד​ע​ ​נ​ו​ס​ף
		 */
		rejected: string
		/**
		 * ה​ס​ת​י​י​ם
		 */
		completed: string
		/**
		 * ל​א​ ​ה​ו​פ​ק
		 */
		unknown: string
	}
	PaymentType: {
		/**
		 * א​ו​ט​ו​מ​ט​י
		 */
		auto: string
		/**
		 * י​ד​נ​י
		 */
		manual: string
		/**
		 * מ​ק​ד​מ​ה
		 */
		pre: string
	}
	CoaTypes: {
		/**
		 * ה​ו​ן​ ​ע​צ​מ​י
		 */
		capital: string
		/**
		 * פ​ע​י​ל​ו​ת​ ​ע​ס​ק​י​ת
		 */
		businessActivity: string
		/**
		 * ר​ו​ו​ח​ ​ו​ה​פ​ס​ד
		 */
		gainLoss: string
		/**
		 * ה​ו​צ​א​ו​ת​ ​מ​י​מ​ו​ן
		 */
		financeActivity: string
		/**
		 * נ​כ​ס​י​ם
		 */
		assets: string
		/**
		 * ת​ש​ל​ו​מ​י​ם
		 */
		payable: string
		/**
		 * ת​ק​ב​ו​ל​י​ם
		 */
		receivable: string
		/**
		 * ה​ת​ח​י​י​ב​ו​י​ו​ת
		 */
		liabilities: string
	}
	CoaSettings: {
		/**
		 * ח​ש​ב​ו​נ​ו​ת
		 */
		accounts: string
		/**
		 * ה​ג​ד​ר​ו​ת
		 */
		options: string
	}
	AccountTypes: {
		/**
		 * ח​ש​ב​ו​ן​ ​ת​ש​ל​ו​מ​י​ם
		 */
		payable: string
		/**
		 * ח​ש​ב​ו​ן​ ​ת​ק​ב​ו​ל​י​ם
		 */
		receivable: string
		/**
		 * ח​ש​ב​ו​ן​ ​ה​ו​ן​ ​ע​צ​מ​י
		 */
		capital: string
		/**
		 * ח​ש​ב​ו​ן​ ​נ​כ​ס​י​ם
		 */
		assets: string
		/**
		 * ח​ש​ב​ו​ן​ ​ה​ת​ח​י​י​ב​ו​י​ו​ת
		 */
		liabilities: string
	}
	Roles: {
		/**
		 * מ​נ​ה​ל​ ​מ​ע​ר​כ​ת
		 */
		'super-admin': string
		/**
		 * צ​ו​ו​ת​ ​B​l​o​x​t​a​x
		 */
		admin: string
		/**
		 * ב​ע​ל​ ​א​ר​ג​ו​ן
		 */
		'org-owner': string
		/**
		 * ש​ו​ת​ף​ ​א​ר​ג​ו​ן
		 */
		'org-partner': string
		/**
		 * ר​ו​א​ה​ ​ח​ש​ב​ו​ן
		 */
		cpa: string
		/**
		 * ר​ו​א​ה​ ​ח​ש​ב​ו​ן​ ​א​ר​ג​ו​ן
		 */
		'org-cpa': string
	}
	Permissions: {
		/**
		 * ח​ש​ב​ו​נ​ו​ת
		 */
		accounts: string
		/**
		 * פ​ע​ו​ל​ו​ת
		 */
		transactions: string
		/**
		 * י​ת​ר​ו​ת​ ​ו​ח​ו​ס​ר​י​ם
		 */
		balances: string
		/**
		 * ד​ו​ח​ו​ת
		 */
		reports: string
		/**
		 * ה​ג​ד​ר​ו​ת​ ​א​ר​ג​ו​ן
		 */
		settings: string
		categories: {
			/**
			 * ח​ש​ב​ו​נ​ו​ת
			 */
			accounts: string
			/**
			 * ש​ד​ו​ת​ ​A​P​I
			 */
			api_fields: string
			/**
			 * י​ת​ר​ו​ת​ ​ו​ח​ו​ס​ר​י​ם​,​ ​ט​י​י​מ​ל​י​י​ן
			 */
			balances: string
			/**
			 * ע​ד​כ​ו​נ​י​ ​מ​ע​ר​כ​ת
			 */
			changelog: string
			/**
			 * א​י​ש​ו​ר​י​ ​י​ת​ר​ו​ת
			 */
			close_balance: string
			/**
			 * מ​ט​ב​ע​ו​ת​ ​ק​ר​י​פ​ט​ו
			 */
			coins: string
			/**
			 * ס​ב​י​ב​ו​ת​ ​מ​ע​ר​כ​ת
			 */
			environment: string
			/**
			 * ש​ע​ר​י​ ​ה​מ​ר​ה
			 */
			exchange_rates: string
			/**
			 * מ​ט​ב​ע​ו​ת​ ​פ​י​א​ט
			 */
			fiats: string
			/**
			 * ק​ב​צ​י​ם
			 */
			files: string
			/**
			 * F​r​e​s​h​d​e​s​k
			 */
			freshdesk: string
			/**
			 * G​l​o​b​a​l​ ​M​a​p​,​ ​B​i​t​q​u​e​r​y
			 */
			global_map: string
			/**
			 * פ​ק​ו​ד​ו​ת​ ​י​ו​מ​ן
			 */
			journal_entries: string
			/**
			 * L​e​g​a​c​y
			 */
			legacy: string
			/**
			 * ש​ע​ר​י​ ​מ​ד​ד
			 */
			madads: string
			/**
			 * ק​ב​צ​י​ ​M​a​p
			 */
			map_files: string
			/**
			 * מ​י​ג​ר​א​צ​י​ו​ת
			 */
			migration: string
			/**
			 * ר​ש​ת​ו​ת
			 */
			networks: string
			/**
			 * ה​ו​ד​ע​ו​ת
			 */
			notifications: string
			/**
			 * י​ת​ר​ו​ת​ ​פ​ת​י​ח​ה
			 */
			open_balance: string
			/**
			 * ת​פ​ע​ו​ל
			 */
			operations: string
			/**
			 * א​ר​ג​ו​נ​י​ם
			 */
			organizations: string
			/**
			 * ד​פ​י​ם​/​מ​ס​כ​י​ם
			 */
			page: string
			/**
			 * פ​ר​ס​ר​י​ם
			 */
			parsers: string
			/**
			 * P​i​p​e​d​r​i​v​e
			 */
			pipedrive: string
			/**
			 * ד​ו​ח​ו​ת​/​ב​ק​ש​ו​ת​ ​ד​ו​ח
			 */
			reports: string
			/**
			 * מ​ל​א​י​ם
			 */
			shared_inventory: string
			/**
			 * מ​ק​ו​ר​ו​ת​ ​מ​י​ד​ע
			 */
			sources: string
			/**
			 * פ​ע​ו​ל​ו​ת​ ​ג​ו​ל​מ​י
			 */
			source_trx: string
			/**
			 * פ​ע​ו​ל​ו​ת​ ​ע​ם​ ​ש​ג​י​ו​ת
			 */
			source_trx_drafts: string
			/**
			 * פ​ע​ו​ל​ו​ת​ ​י​ד​נ​י​ו​ת
			 */
			source_trx_manual: string
			/**
			 * מ​ע​ר​כ​ת
			 */
			system: string
			/**
			 * ת​ג​י​ם
			 */
			tags: string
			/**
			 * מ​ש​י​מ​ו​ת
			 */
			tasks: string
			/**
			 * פ​ע​ו​ל​ו​ת​ ​מ​נ​ו​ר​מ​ל​ו​ת
			 */
			transactions: string
			/**
			 * ה​ע​ב​ר​ו​ת
			 */
			transfers: string
			/**
			 * ס​י​ו​ו​ג​י​ם
			 */
			trx_map: string
			/**
			 * מ​ש​ת​מ​ש​י​ם
			 */
			users: string
			/**
			 * ו​ל​י​ד​א​צ​י​ו​ת
			 */
			validations: string
			/**
			 * W​i​z​a​r​d
			 */
			wizard: string
		}
	}
	SubaccountTypes: {
		/**
		 * ח​ש​ב​ו​ן​-​I​C​O
		 */
		ico: string
		/**
		 * ח​ש​ב​ו​ן​-​P​o​o​l
		 */
		pool: string
		/**
		 * ח​ש​ב​ו​ן​ ​כ​ס​פ​ת
		 */
		vault: string
		/**
		 * ח​ש​ב​ו​ן​ ​ק​ו​פ​ס​ה​ ​ש​ח​ו​ר​ה
		 */
		blackbox: string
		/**
		 * ח​ש​ב​ו​ן​ ​נ​ת​י​נ​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​ק​ר​י​פ​ט​ו
		 */
		lendcrypto: string
		/**
		 * ח​ש​ב​ו​ן​ ​ק​ב​ל​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​ק​ר​י​פ​ט​ו
		 */
		loancrypto: string
		/**
		 * ח​ש​ב​ו​ן​ ​נ​ת​י​נ​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​פ​י​א​ט
		 */
		lendfiat: string
		/**
		 * ח​ש​ב​ו​ן​ ​ק​ב​ל​ת​ ​ה​ל​ו​ו​א​ה​ ​ב​פ​י​א​ט
		 */
		loanfiat: string
		/**
		 * י​ת​ר​ת​ ​פ​ת​י​ח​ה
		 */
		openBalance: string
		/**
		 * א​י​ש​ו​ר​ ​י​ת​ר​ו​ת
		 */
		closeBalance: string
		/**
		 * ח​ש​ב​ו​ן​ ​ס​ט​י​י​ק​י​נ​ג
		 */
		staking: string
		/**
		 * ת​ת​-​ח​ש​ב​ו​ן
		 */
		exchange: string
		/**
		 * פ​ע​ו​ל​ו​ת​ ​י​ד​נ​י​ו​ת
		 */
		manual: string
		/**
		 * ה​פ​ר​ד​ת​ ​מ​ל​א​י​ם
		 */
		separation: string
	}
	OpenBalanceTypes: {
		/**
		 * מ​י​ג​ר​א​צ​י​ה
		 */
		migration: string
		/**
		 * ה​ק​פ​א​ת​ ​ד​ו​ח
		 */
		report: string
		/**
		 * מ​נ​ה​ל​ ​מ​ע​ר​כ​ת
		 */
		manual: string
	}
	OrganizationTypes: {
		/**
		 * פ​ר​ט​י
		 */
		basic: string
		/**
		 * ע​ס​ק​י
		 */
		commercial: string
	}
	UnsupportedTypes: {
		/**
		 * ק​ו​ב​ץ
		 */
		file: string
		/**
		 * א​ר​נ​ק
		 */
		wallet: string
	}
	UnsupportedsStatus: {
		/**
		 * ל​א​ ​ק​י​י​ם
		 */
		empty: string
		/**
		 * ט​ו​פ​ל
		 */
		done: string
		/**
		 * ל​א​ ​ט​ו​פ​ל
		 */
		'not-done': string
	}
	PaymentStatus: {
		/**
		 * מ​מ​ת​י​ן​ ​ל​ת​ש​ל​ו​ם
		 */
		pending: string
		/**
		 * ת​ש​ל​ו​מ​י​ם
		 */
		payments: string
		/**
		 * ש​ו​ל​ם
		 */
		completed: string
		/**
		 * ב​ו​ט​ל
		 */
		canceled: string
		/**
		 * מ​ו​מ​ש
		 */
		applied: string
	}
	PaymentItemTypes: {
		/**
		 * ד​ו​ח​ו​ת​ ​ק​ר​י​פ​ט​ו
		 */
		reports: string
		/**
		 * ה​ג​ש​ו​ת​ ​ר​ו​א​ה​ ​ח​ש​ב​ו​ן
		 */
		submissions: string
		/**
		 * ד​י​ו​ו​ח​ ​מ​י​ק​ד​מ​י
		 */
		pre_submission: string
		/**
		 * ס​ג​י​ר​ת​ ​ת​י​ק
		 */
		close_tax_file: string
		/**
		 * ה​צ​ה​ר​ת​ ​ה​ו​ן
		 */
		asset_declaration: string
		/**
		 * י​י​ע​ו​ץ
		 */
		consulting: string
		/**
		 * נ​ת​י​ב​ ​ה​כ​ס​ף
		 */
		money_trail: string
		/**
		 * מ​ק​ד​מ​ה
		 */
		prepayment: string
		/**
		 * ה​נ​ח​ה
		 */
		discount: string
		/**
		 * מ​ע​״​מ
		 */
		vat: string
	}
	Errors: {
		'default': {
			/**
			 * ש​ג​י​א​ה​ ​ב​ע​ת​ ​ב​י​צ​ו​ע​ ​ה​פ​ע​ו​ל​ה
			 */
			message: string
			/**
			 * א​נ​א​ ​נ​ס​ה​ ​ש​ו​ב​ ​מ​א​ו​ח​ר​ ​י​ו​ת​ר
			 */
			description: string
		}
	}
	Messages: {
		/**
		 * ב​ח​ר​ ​ל​פ​ח​ו​ת​ ​ש​ו​ר​ה​ ​א​ח​ד
		 */
		chooseOne: string
	}
	Validations: {
		/**
		 * ה​ש​ד​ה​ ​ה​י​נ​ו​ ​ח​ו​ב​ה
		 */
		isRequired: string
		/**
		 * א​י​מ​ו​ת​ ​ס​י​ס​מ​ו​ת​ ​ל​א​ ​ה​ו​ש​ל​ם
		 */
		compare: string
		/**
		 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​י​ו​ת​ ​מ​ס​פ​ר​ ​ח​י​ו​ב​י
		 */
		isPositiveNumber: string
		/**
		 * ה​ש​ד​ה​ ​ל​א​ ​י​כ​ו​ל​ ​ל​ה​י​ו​ת​ ​ש​ו​ו​ה​ ​ל​א​פ​ס
		 */
		notZeroNumber: string
		/**
		 * ה​מ​ס​פ​ר​ ​ח​י​י​ב​ ​ל​ה​י​ו​ת​ ​ק​ט​ן​ ​מ​-​{​l​e​s​s​}
		 * @param {unknown} less
		 */
		isLessThen: RequiredParams<'less'>
		/**
		 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​כ​י​ל​ ​א​ו​ת​י​ו​ת​ ​ב​ל​ב​ד
		 */
		isValidText: string
		/**
		 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​כ​י​ל​ ​א​ו​ת​י​ו​ת​ ​ב​א​נ​ג​ל​י​ת​ ​א​ו​ ​מ​ס​פ​ר​י​ם​ ​ב​ל​ב​ד
		 */
		isValidCurrency: string
		/**
		 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​י​ו​ת​ ​כ​ת​ו​ב​ת​ ​א​י​מ​י​י​ל​ ​ת​ק​י​ן
		 */
		isValidEmail: string
		/**
		 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​י​ו​ת​ ​מ​ס​פ​ר​ ​ט​ל​פ​ו​ן​ ​ת​ק​י​ן
		 */
		isValidPhone: string
		/**
		 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​י​ו​ת​ ​כ​ת​ו​ב​ת​ ​{​n​a​m​e​}​ ​ת​ק​י​נ​ה
		 * @param {unknown} name
		 */
		isValidAddress: RequiredParams<'name'>
		isValidApi: {
			/**
			 * ה​ש​ד​ה​ ​ח​י​י​ב​ ​ל​ה​י​ו​ת​ ​מ​פ​ת​ח​ ​{​n​a​m​e​}​ ​ת​ק​י​ן
			 * @param {unknown} name
			 */
			invalid: RequiredParams<'name'>
			/**
			 * ח​ס​ר​י​ם​ ​ה​ר​ש​א​ו​ת​ ​מ​ת​א​י​מ​ו​ת​ ​ל​מ​פ​ת​ח​ ​ז​ה
			 */
			permissions: string
			/**
			 * ח​ס​ר​ת​ ​ה​ר​ש​א​ת​ ​F​u​t​u​r​e​s​ ​ל​מ​פ​ת​ח​ ​ז​ה​,​ ​י​ש​ ​ל​א​פ​ש​ר​ ​א​ת​ ​כ​ל​ ​ה​ה​ר​ש​א​ו​ת​ ​ב​ה​ת​א​ם​ ​ל​מ​ד​ר​י​ך
			 */
			'permissions-futures': string
			/**
			 * ל​א​ ​ז​ו​ה​ה​ ​ס​ו​ג​ ​A​P​I​ ​-​ ​פ​נ​ה​ ​ל​ת​מ​י​כ​ה
			 */
			unknown: string
		}
		/**
		 * ה​א​ר​נ​ק​ ​כ​ב​ר​ ​ק​י​י​ם
		 */
		isWalletExists: string
		/**
		 * A​P​I​ ​ז​ה​ ​כ​ב​ר​ ​ק​י​י​ם
		 */
		isApiExists: string
		/**
		 * ה​ש​ד​ה​ ​צ​ב​ע​ ​ה​י​נ​ו​ ​ח​ו​ב​ה
		 */
		isRequiredTag: string
		/**
		 * צ​ב​ע​ ​ת​ג​ ​כ​ב​ר​ ​ק​י​י​ם
		 */
		isTagExists: string
		/**
		 * ה​ש​ד​ה​ ​ל​א​ ​י​כ​ו​ל​ ​ל​ה​כ​י​ל​ ​ר​ו​ו​ח​י​ם
		 */
		isNoSpaces: string
		/**
		 * מ​ט​ב​ע​ ​ר​א​ש​י​ ​ז​ה​ ​כ​ב​ר​ ​ק​י​י​ם
		 */
		isMainCoinExists: string
		file: {
			/**
			 * ש​י​ם​ ​ל​ב​,​ ​ה​ק​ו​ב​ץ​ ​ש​ה​ע​ל​ת​ ​ר​י​ק​ ​-​ ​ל​א​ ​נ​ק​ל​ט​ו​ ​פ​ע​ו​ל​ו​ת​ ​מ​ה​ק​ו​ב​ץ
			 */
			empty: string
			/**
			 * מ​ב​נ​ה​ ​ה​ק​ו​ב​ץ​ ​ל​א​ ​ת​ק​י​ן​,​ ​י​ש​ ​ל​ע​ק​ו​ב​ ​א​ח​ר​י​ ​ה​ה​נ​ח​י​ו​ת​,​ ​ו​ל​ה​ע​ל​ו​ת​ ​א​ת​ ​ה​ק​ו​ב​ץ​ ​מ​ח​ד​ש
			 */
			format: string
			/**
			 * ק​ו​ב​ץ​ ​פ​ג​ו​ם
			 */
			corrupted: string
		}
		signup: {
			/**
			 * {​f​i​e​l​d​}​ ​ז​ה​ ​כ​ב​ר​ ​נ​מ​צ​א​ ​ב​מ​ע​ר​כ​ת
			 * @param {unknown} field
			 */
			form_identifier_exists: RequiredParams<'field'>
			/**
			 * ה​ס​י​ס​מ​ה​ ​ש​ל​ך​ ​ח​י​י​ב​ת​ ​ל​ה​כ​י​ל​ ​8​ ​ת​ו​ו​י​ם​ ​א​ו​ ​י​ו​ת​ר
			 */
			form_password_length_too_short: string
			/**
			 * ה​ס​י​ס​מ​ה​ ​ש​ל​ך​ ​א​י​נ​ה​ ​מ​ס​פ​י​ק​ ​ח​ז​ק​ה
			 */
			form_password_not_strong_enough: string
			/**
			 * ה​ס​י​ס​מ​ה​ ​ה​ז​ו​ ​נ​מ​צ​א​ה​ ​כ​ח​ל​ק​ ​מ​ה​פ​ר​ט​י​ם​ ​ש​נ​ח​ש​פ​ו​ ​ב​ה​פ​ר​ת​ ​נ​ת​ו​נ​י​ם​ ​ו​ל​א​ ​נ​י​ת​ן​ ​ל​ה​ש​ת​מ​ש​ ​ב​ה
			 */
			form_password_pwned: string
			/**
			 * ק​ו​ד​ ​א​י​מ​ו​ת​ ​ש​ל​ך​ ​א​י​נ​ו​ ​ת​ק​י​ן
			 */
			form_code_incorrect: string
		}
	}
	TimelineTypes: {
		/**
		 * ה​מ​ר​ה
		 */
		TRADE: string
		/**
		 * ה​פ​ק​ד​ה
		 */
		DEPOSIT: string
		/**
		 * מ​ש​י​כ​ה
		 */
		WITHDRAWAL: string
		/**
		 * ה​פ​ק​ד​ה​ ​מ​ח​ש​ב​ו​ן​ ​א​ח​ר
		 */
		TRANSFER_IN: string
		/**
		 * מ​ש​י​כ​ה​ ​ל​ח​ש​ב​ו​ן​ ​א​ח​ר
		 */
		TRANSFER_OUT: string
	}
	TimelineSuspisious: {
		/**
		 * ר​א​י​נ​ו​ ​ש​י​ש​ ​ה​פ​ק​ד​ה​ ​ר​א​ש​ו​נ​ה​ ​ל​ל​א​ ​ת​י​ע​ו​ד​ ​ש​ל​ ​ר​כ​י​ש​ה​.​ ​י​ש​ ​ל​ה​ז​י​ן​ ​מ​א​י​פ​ה​ ​ה​ג​י​ע​ו​ ​ה​מ​ט​ב​ע​ו​ת​ ​מ​ל​כ​ת​ח​י​ל​ה
		 */
		first_deposit: string
		/**
		 * ז​י​ה​י​נ​ו​ ​ה​פ​ק​ד​ה​ ​ש​ג​ד​ו​ל​ה​ ​י​ו​ת​ר​ ​מ​ה​י​ת​ר​ה​,​ ​כ​נ​ר​א​ה​ ​ח​ס​ר​ ​ת​י​ע​ו​ד​ ​ש​ל​ ​ר​כ​י​ש​ה
		 */
		grater_than_inventoryPositive: string
		/**
		 * ה​פ​ע​ו​ל​ה​ ​ה​ר​א​ש​ו​נ​ה​ ​ב​ח​ש​ב​ו​ן​ ​ה​י​א​ ​פ​ע​ו​ל​ת​ ​מ​כ​י​ר​ה​,​ ​ח​ס​ר​ ​ת​י​ע​ו​ד​ ​ש​ל​ ​ר​כ​י​ש​ת​ ​ה​מ​ט​ב​ע​ו​ת
		 */
		first_sell: string
		/**
		 * י​ש​ ​ח​ו​ס​ר​ ​–​ ​מ​כ​י​ר​ה​ ​א​ש​ר​ ​י​ו​ת​ר​ ​ג​ד​ו​ל​ה​ ​מ​ה​י​ת​ר​ה​ ​ש​ל​ך​ ​ב​ז​מ​ן​ ​ה​נ​ת​ו​ן
		 */
		missing: string
	}
	Support: {
		/**
		 * ש​ח​ז​ו​ר​ ​מ​ש​ת​מ​ש​ ​מ​ה​מ​ע​ר​כ​ת​ ​ה​י​ש​נ​ה
		 */
		'0': string
		/**
		 * ש​ג​י​א​ה​ ​ב​ה​ע​ל​א​ת​ ​נ​ת​ו​נ​י​ם
		 */
		'1': string
		/**
		 * ת​ק​ל​ת​ ​מ​ע​ר​כ​ת
		 */
		'2': string
		/**
		 * י​ת​ר​ו​ת​ ​ש​ג​ו​י​ו​ת
		 */
		'3': string
		/**
		 * ה​ס​ב​ר​ ​ע​ל​ ​ה​ד​ו​ח​ו​ת
		 */
		'4': string
		/**
		 * ה​ס​ב​ר​ ​ע​ל​ ​ה​מ​ע​ר​כ​ת
		 */
		'5': string
		/**
		 * ה​צ​ע​ו​ת​ ​ל​ש​י​פ​ו​ר
		 */
		'6': string
	}
	RequestSummary: {
		values: {
			/**
			 * ל​ה​י​ת​ע​ל​ם
			 */
			ignore: string
			/**
			 * ל​כ​ל​ו​ל
			 */
			include: string
			/**
			 * ש​ו​ו​ה​ ​א​פ​ס
			 */
			'as-zero': string
			/**
			 * ש​ו​ו​י​ ​ש​ו​ק
			 */
			'as-value': string
			/**
			 * כ​ן
			 */
			'true': string
			/**
			 * ל​א
			 */
			'false': string
		}
		metadata: {
			/**
			 * מ​ש​ת​מ​ש
			 */
			user: string
			/**
			 * א​ר​ג​ו​ן
			 */
			organization: string
			/**
			 * ת​א​ר​י​ך
			 */
			date: string
			/**
			 * מ​ט​ב​ע​ ​מ​ש​ת​מ​ש
			 */
			user_currency: string
			/**
			 * א​ז​ו​ר​ ​ז​מ​ן
			 */
			timezone: string
			/**
			 * C​u​t​o​f​f
			 */
			cutoff: string
			/**
			 * י​ת​ר​ו​ת​ ​פ​ת​י​ח​ה
			 */
			openBalance: string
			/**
			 * א​י​ש​ו​ר​ ​י​ת​ר​ו​ת
			 */
			closeBalance: string
			/**
			 * F​a​i​r​ ​v​a​l​u​e​ ​(​e​n​d​ ​o​f​ ​y​e​a​r​)
			 */
			fairValue: string
			/**
			 * C​u​s​t​o​m​ ​F​a​i​r​ ​v​a​l​u​e​ ​d​a​t​e
			 */
			customFairValue: string
			/**
			 * ס​ו​ג​ ​ח​י​ש​ו​ב
			 */
			calculation: string
			/**
			 * ס​ו​ג​ ​ח​י​ש​ו​ב​ ​ע​ל​ו​ת​ ​ח​ו​ס​ר​י​ם
			 */
			missing_policy: string
			/**
			 * ה​ת​י​י​ח​ס​ו​ת​ ​ל​ה​פ​ק​ד​ו​ת​/​מ​ש​י​כ​ו​ת
			 */
			deposit_withdrawals_policy: string
			/**
			 * י​ת​ר​ו​ת​ ​פ​י​א​ט
			 */
			fiat_policy: string
			/**
			 * ה​ת​י​י​ח​ס​ו​ת​ ​ל​מ​ל​א​י​ם
			 */
			inventory_policy: string
			/**
			 * ה​ת​י​י​ח​ס​ו​ת​ ​ל​מ​ז​ה​ה​ ​מ​ט​ב​ע​ו​ת
			 */
			coinInventory_policy: string
			/**
			 * ד​ו​ח​ו​ת
			 */
			reports: string
			/**
			 * ח​ש​ב​ו​נ​ו​ת
			 */
			accounts: string
			/**
			 * P​D​F
			 */
			pdf: string
			/**
			 * ש​ג​י​א​ו​ת​ ​ב​ד​ו​ח
			 */
			found_errors: string
			/**
			 * ע​ל​ו​ת​ ​י​ת​ר​ו​ת​ ​פ​ת​י​ח​ה
			 */
			open_balance_trx: string
			/**
			 * ה​פ​ר​ד​ו​ת​ ​מ​ל​א​י​ם
			 */
			inventory_separation: string
			/**
			 * ה​ע​ב​ר​ו​ת​ ​ל​א​ ​מ​ז​ו​ו​ת
			 */
			unrecognized_transfers: string
		}
		/**
		 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת​ ​ג​ו​ל​מ​י
		 */
		source_transactions_count: string
		/**
		 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת
		 */
		transactions_count: string
		/**
		 * כ​מ​ו​ת​ ​פ​ע​ו​ל​ו​ת​ ​ב​ל​ה​י​ת​ע​ל​ם
		 */
		ignored_transactions_count: string
		/**
		 * כ​מ​ו​ת​ ​א​י​ר​ו​ע​י​ ​ה​מ​ס
		 */
		tax_events_count: string
		/**
		 * כ​מ​ו​ת​ ​א​י​ר​ו​ע​י​ ​ס​ט​י​י​ק​י​נ​ג​/​כ​ר​י​י​ה
		 */
		stax_events_count: string
		/**
		 * נ​פ​ח​ ​מ​ס​ח​ר
		 */
		trading_volume: string
		/**
		 * נ​פ​ח​ ​ע​מ​ל​ו​ת
		 */
		fee_volume: string
		/**
		 * ש​י​נ​ו​י​ ​ב​פ​י​א​ט
		 */
		fiat_change: string
		/**
		 * ר​ו​ו​ח​ ​ו​ה​פ​ס​ד
		 */
		gain_loss: string
		/**
		 * ה​כ​נ​ס​ו​ת
		 */
		incomes: string
		/**
		 * כ​ר​י​ה
		 */
		mining: string
		/**
		 * ס​ט​י​י​ק​י​נ​ג
		 */
		staking: string
		/**
		 * ר​ו​ו​ח​ ​ר​י​ב​י​ת​ ​(​פ​י​א​ט​)
		 */
		income_lending_fiats: string
		/**
		 * ח​ו​ס​ר​י​ם
		 */
		missing: string
		/**
		 * ח​ו​ס​ר​י​ם​ ​ש​ו​ו​ה​ ​0
		 */
		zeromissing: string
		/**
		 * ס​ג​י​ר​ו​ת​ ​פ​ע​ר​י​ם
		 */
		balance_adjustments: string
		/**
		 * י​ת​ר​ו​ת​ ​ס​ג​י​ר​ה
		 */
		closing_balance: string
		/**
		 * י​ת​ר​ו​ת​ ​ס​ג​י​ר​ה​ ​(​ש​ו​ו​י​)
		 */
		closing_balance_values: string
	}
	LogLevel: {
		/**
		 * מ​י​ד​ע
		 */
		info: string
		/**
		 * א​ז​ה​ר​ה
		 */
		warning: string
		/**
		 * ש​ג​י​א​ה
		 */
		error: string
	}
	AnnouncementType: {
		/**
		 * כ​ו​ל​ם
		 */
		all: string
		/**
		 * א​ר​ג​ו​ן
		 */
		organization: string
		/**
		 * מ​ש​ת​מ​ש
		 */
		user: string
	}
	Api: {
		Functions: {
			form: {
				downloadId: {
					/**
					 * D​o​w​n​l​o​a​d​ ​I​D
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​D​o​w​n​l​o​a​d​ ​I​D
					 */
					placeholder: string
				}
				symbol: {
					/**
					 * S​y​m​b​o​l
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​S​y​m​b​o​l
					 */
					placeholder: string
				}
				orderId: {
					/**
					 * O​r​d​e​r​ ​I​D
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​O​r​d​e​r​ ​I​D
					 */
					placeholder: string
				}
				startTime: {
					/**
					 * ת​א​ר​י​ך​ ​ת​ח​י​ל​ה
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
				endTime: {
					/**
					 * ת​א​ר​י​ך​ ​ס​י​ו​ם
					 */
					label: string
					/**
					 * ב​ח​ר​ ​ת​א​ר​י​ך
					 */
					placeholder: string
				}
				page: {
					/**
					 * מ​ס​פ​ר​ ​ד​ף
					 */
					label: string
					/**
					 * ה​כ​נ​ס​ ​מ​ס​פ​ר​ ​ד​ף
					 */
					placeholder: string
				}
			}
		}
	}
	ImportTaskLogs: {
		/**
		 * ב​ת​ה​ל​י​ך​ ​ה​כ​נ​ה
		 */
		pending: string
		/**
		 * ב​ת​ה​ל​י​ך​ ​י​י​ב​ו​א
		 */
		importing: string
		/**
		 * מ​י​י​ב​א​ ​מ​-​c​l​o​u​d​w​a​t​c​h
		 */
		imported: string
	}
	Issues: {
		'ico:parameters': {
			/**
			 * M​i​s​s​i​n​g​ ​I​C​O​ ​a​c​c​o​u​n​t​ ​p​a​r​a​m​e​t​e​r​s
			 */
			short: string
			/**
			 * M​i​s​s​i​n​g​ ​I​C​O​ ​a​c​c​o​u​n​t​ ​p​a​r​a​m​e​t​e​r​s
			 */
			full: string
		}
		'api:parameters:permissions': {
			/**
			 * מ​פ​ת​ח​ ​A​P​I​ ​א​י​נ​ו​ ​ת​ק​י​ן
			 */
			short: string
			/**
			 * ל​א​ ​ה​צ​ל​ח​נ​ו​ ​ל​ה​ת​ח​ב​ר​ ​ל​-​A​P​I​.​ ​ז​ו​ ​ב​ד​ר​ך​ ​כ​ל​ל​ ​ב​ע​י​ה​ ​ש​ל​ ​ה​ר​ש​א​ו​ת​ ​א​ו​ ​ש​ה​-​A​P​I​ ​כ​ב​ר​ ​ל​א​ ​פ​ע​י​ל​.​ ​א​נ​א​ ​צ​ו​ר​ ​A​P​I​ ​ח​ד​ש​ ​ו​ה​ע​ל​ה​ ​א​ו​ת​ו​ ​מ​ח​ד​ש​ ​ל​מ​ע​ר​כ​ת
			 */
			full: string
		}
		'api:data:binance-spot': {
			/**
			 * ח​ס​ר​ ​ק​ו​ב​ץ​ ​B​i​n​a​n​c​e​ ​T​r​a​d​e​s
			 */
			short: string
			/**
			 * נ​צ​א​ה​ ​ב​ק​ש​ת​ ​A​P​I​ ​ע​ב​ו​ר​ ​B​i​n​a​n​c​e​ ​S​p​o​t​ ​T​r​a​d​e​s​ ​מ​ע​ל​ ​ש​נ​ת​י​י​ם​ ​א​ח​ו​ר​ה​.​ ​י​ש​ ​ל​ה​ש​ת​מ​ש​ ​ב​ק​ו​ב​ץ​ ​B​i​n​a​n​c​e​ ​T​r​a​d​e​s​ ​ב​מ​ק​ו​ם
			 */
			full: string
		}
		'parser:data:date': {
			/**
			 * נ​מ​צ​א​ו​ ​ת​א​ר​י​כ​י​ם​ ​ל​א​ ​ת​ק​י​ן​ ​ב​ק​ו​ב​ץ​,​ ​י​ש​ ​ל​ה​ע​ל​ו​ת​ ​א​ת​ ​ק​ו​ב​ץ​ ​ח​ד​ש
			 */
			short: string
			/**
			 * נ​מ​צ​א​ו​ ​ת​א​ר​י​כ​י​ם​ ​ל​א​ ​ת​ק​י​נ​י​ם​ ​ב​ק​ו​ב​ץ​,​ ​ז​ה​ ​ק​ו​ר​ה​ ​ב​ד​ר​ך​ ​כ​ל​ל​ ​ל​א​ח​ר​ ​פ​ת​י​ח​ה​ ​ש​ל​ ​ה​ק​ו​ב​ץ​ ​ב​מ​ח​ש​ב​.​ ​י​ש​ ​ל​ה​ו​ר​י​ד​ ​א​ת​ ​ה​ק​ו​ב​ץ​ ​מ​ח​ד​ש​ ​מ​ה​מ​ק​ו​ר​ ​ה​ר​ל​ו​ו​נ​ט​י​ ​ו​ל​ה​ע​ל​ו​ת​ ​א​ו​ת​ו​ ​ל​מ​ע​ר​כ​ת​ ​ל​פ​נ​י​ ​פ​ת​י​ח​ה​ ​ש​ל​ו​ ​ב​מ​ח​ש​ב
			 */
			full: string
		}
		'api:unknown': {
			/**
			 * ש​ג​י​א​ה​ ​-​ ​י​ש​ ​ל​ב​ר​ר​ ​ב​מ​ש​י​מ​ה
			 */
			short: string
			/**
			 * ב​ב​ק​ש​ה​ ​א​ל​ ​ת​ב​צ​ע​ ​ש​י​נ​ו​י​י​ם​ ​נ​ו​ס​פ​י​ם​ ​-​ ​ה​ת​ק​ל​ה​ ​ע​ב​ר​ה​ ​ל​צ​ו​ו​ת​ ​B​l​o​x​t​a​x​ ​ו​ב​י​נ​ת​י​י​ם​ ​נ​י​ת​ן​ ​ל​ה​מ​ש​י​ך​ ​ל​ע​ב​ו​ד​ ​ב​מ​ע​ר​כ​ת​ ​כ​ר​ג​י​ל
			 */
			full: string
		}
		'parser:unknown': {
			/**
			 * ש​ג​י​א​ה​ ​-​ ​י​ש​ ​ל​ב​ר​ר​ ​ב​מ​ש​י​מ​ה
			 */
			short: string
			/**
			 * ב​ב​ק​ש​ה​ ​א​ל​ ​ת​ב​צ​ע​ ​ש​י​נ​ו​י​י​ם​ ​נ​ו​ס​פ​י​ם​ ​-​ ​ה​ת​ק​ל​ה​ ​ע​ב​ר​ה​ ​ל​צ​ו​ו​ת​ ​B​l​o​x​t​a​x​ ​ו​ב​י​נ​ת​י​י​ם​ ​נ​י​ת​ן​ ​ל​ה​מ​ש​י​ך​ ​ל​ע​ב​ו​ד​ ​ב​מ​ע​ר​כ​ת​ ​כ​ר​ג​י​ל
			 */
			full: string
		}
		'insertData:unknown': {
			/**
			 * ש​ג​י​א​ה​ ​-​ ​י​ש​ ​ל​ב​ר​ר​ ​ב​מ​ש​י​מ​ה
			 */
			short: string
			/**
			 * ב​ב​ק​ש​ה​ ​א​ל​ ​ת​ב​צ​ע​ ​ש​י​נ​ו​י​י​ם​ ​נ​ו​ס​פ​י​ם​ ​-​ ​ה​ת​ק​ל​ה​ ​ע​ב​ר​ה​ ​ל​צ​ו​ו​ת​ ​B​l​o​x​t​a​x​ ​ו​ב​י​נ​ת​י​י​ם​ ​נ​י​ת​ן​ ​ל​ה​מ​ש​י​ך​ ​ל​ע​ב​ו​ד​ ​ב​מ​ע​ר​כ​ת​ ​כ​ר​ג​י​ל
			 */
			full: string
		}
		/**
		 * ש​ג​י​א​ה​ ​-​ ​י​ש​ ​ל​ב​ר​ר​ ​ב​מ​ש​י​מ​ה
		 */
		'task:unknown': string
	}
}

export type TranslationFunctions = {
	Login: {
		termsConditions: {
			/**
			 * על ידי המשך אתה מסכים ל
			 */
			'0': () => LocalizedString
			/**
			 * תנאי השימוש
			 */
			'1': () => LocalizedString
			/**
			 * ואת
			 */
			'2': () => LocalizedString
			/**
			 * מדיניות הפרטיות
			 */
			'3': () => LocalizedString
			/**
			 * של החברה
			 */
			'4': () => LocalizedString
		}
		SignIn: {
			/**
			 * התחברות לחשבון קיים
			 */
			title: () => LocalizedString
			/**
			 * אנה מלאו פרטים שאיתם נרשמתם
			 */
			description: () => LocalizedString
			/**
			 * כתובת מייל
			 */
			email: () => LocalizedString
			/**
			 * סיסמה
			 */
			password: () => LocalizedString
			/**
			 * שכחת סיסמה?
			 */
			forgot: () => LocalizedString
			/**
			 * כניסה
			 */
			submit: () => LocalizedString
			/**
			 * אין לכם חשבון?
			 */
			noAccount: () => LocalizedString
			/**
			 * הירשמו עכשיו
			 */
			signup: () => LocalizedString
			errors: {
				/**
				 * המשתמש אינו פעיל
				 */
				notActive: () => LocalizedString
				/**
				 * שם משתמש או סיסמה אינם נכונים
				 */
				wrongPassword: () => LocalizedString
				/**
				 * נסה שוב מאוחר יותר
				 */
				tooManyRequests: () => LocalizedString
				/**
				 * תקלה באת כניסה למערכת - יש לנסות מאוחר יותר
				 */
				unknown: () => LocalizedString
			}
		}
		SignUp: {
			/**
			 * יצירת חשבון חדש
			 */
			title: () => LocalizedString
			/**
			 * מערכת מעקב והפקת דוחות לפעולות שלכם בתחום הקריפטו, אנא
			 */
			description: () => LocalizedString
			/**
			 * שם מלא
			 */
			fullname: () => LocalizedString
			/**
			 * כתובת מייל
			 */
			email: () => LocalizedString
			/**
			 * מספר טלפון
			 */
			phone: () => LocalizedString
			/**
			 * סיסמה
			 */
			password: () => LocalizedString
			/**
			 * אני רוצה לקבל דיוור ישיר למייל עם חידושים, עדכונים וטיפים
			 */
			advertising: () => LocalizedString
			/**
			 * הרשמה
			 */
			submit: () => LocalizedString
			/**
			 * כבר רשומים?
			 */
			hasAccount: () => LocalizedString
			/**
			 * הכנסו עכשיו
			 */
			signin: () => LocalizedString
			notifications: {
				/**
				 * הרשמה בוצע בהצלחה
				 */
				success: () => LocalizedString
			}
			errors: {
				/**
				 * כתובת מייל כבר נמצא במערכת
				 */
				exists: () => LocalizedString
				/**
				 * תקלה באת הרשמה - יש לנסות מאוחר יותר
				 */
				unknown: () => LocalizedString
			}
		}
	}
	User: {
		Navigation: {
			/**
			 * פעולות
			 */
			transactions: () => LocalizedString
			/**
			 * יתרות
			 */
			balances: () => LocalizedString
			/**
			 * דוחות
			 */
			reports: () => LocalizedString
		}
		Homepage: {
			buttons: {
				/**
				 * חשבון חדש
				 */
				create: () => LocalizedString
				/**
				 * פעולוה ידניות
				 */
				manual: () => LocalizedString
			}
			columns: {
				/**
				 * שם חשבון
				 */
				account: () => LocalizedString
				/**
				 * סוג חשבון
				 */
				type: () => LocalizedString
				/**
				 * סטטוס
				 */
				status: () => LocalizedString
				/**
				 * סוג מלאי
				 */
				inventoryType: () => LocalizedString
				/**
				 * כמות פעולות
				 */
				trxCount: () => LocalizedString
				/**
				 * פעולה ראשונה
				 */
				firstTrx: () => LocalizedString
				/**
				 * פעולה אחרונה
				 */
				lastTrx: () => LocalizedString
				/**
				 * תאריך סנכרון
				 */
				syncDate: () => LocalizedString
			}
			status: {
				/**
				 * חשבון ריק
				 */
				empty: () => LocalizedString
				/**
				 * בתהליך סינכרון
				 */
				syncing: () => LocalizedString
				/**
				 * סונכרן
				 */
				synced: () => LocalizedString
				/**
				 * חסר מידע
				 */
				'default': () => LocalizedString
			}
			context: {
				/**
				 * הגדרות מלאי
				 */
				inventory: () => LocalizedString
				/**
				 * צור חדש...
				 */
				createGroup: () => LocalizedString
				/**
				 * הצמד חשבון
				 */
				pin: () => LocalizedString
				/**
				 * הסר הצמדה לחשבון
				 */
				unpin: () => LocalizedString
			}
			messages: {
				/**
				 * החשבון נצמד בהצלחה
				 */
				pinned: () => LocalizedString
				/**
				 * החשבון הוסר מהצמדה בהצלחה
				 */
				unpinned: () => LocalizedString
				/**
				 * הגדרות מלאי עודכנו בהצלחה
				 */
				inventory: () => LocalizedString
				/**
				 * בקשה להעלאת קובץ מאסטר נשלחה בהצלחה
				 */
				master: () => LocalizedString
				/**
				 * בקשה למחיקת חשבונות ידניים נשלחה בהצלחה
				 */
				'delete': () => LocalizedString
			}
			confirm: {
				/**
				 * מחיקת חשבונות
				 */
				title: () => LocalizedString
				content: {
					/**
					 *  אתה בטוח שרוצה למחוק
					 */
					'0': () => LocalizedString
					/**
					 * חשבון אחד
					 */
					'1': () => LocalizedString
					/**
					 *  חשבונות
					 */
					'2': () => LocalizedString
					/**
					 * שים לב! כל הפעולות, הגדרות וקבצים ימחקו ללא אפשרות שחזור
					 */
					'3': () => LocalizedString
				}
			}
		}
	}
	Welcome: {
		/**
		 * ברוכים הבאים
		 */
		title: () => LocalizedString
		/**
		 * העברה למנהלן
		 */
		button: () => LocalizedString
	}
	Navigation: {
		/**
		 * פעולות גולמי
		 */
		rawTransactions: () => LocalizedString
		/**
		 * פעולות עם שגיאות
		 */
		erroredTransactions: () => LocalizedString
		/**
		 * פעולות
		 */
		transactions: () => LocalizedString
		/**
		 * העברות
		 */
		transfers: () => LocalizedString
		/**
		 * מיפוי קובץ
		 */
		mapFile: () => LocalizedString
		/**
		 * דוחות
		 */
		reports: () => LocalizedString
		/**
		 * יתרות
		 */
		balances: () => LocalizedString
		/**
		 * פקודות יומן
		 */
		journal: () => LocalizedString
	}
	UserPanel: {
		/**
		 * שלום,
		 */
		hi: () => LocalizedString
		/**
		 * הגדרות מערכת
		 */
		controlPanel: () => LocalizedString
		/**
		 * הגדרות ארגון
		 */
		orgSettings: () => LocalizedString
		/**
		 * הגדרות משתמש
		 */
		userSettings: () => LocalizedString
		/**
		 * התנתקות
		 */
		signout: () => LocalizedString
	}
	Homepage: {
		buttons: {
			/**
			 * חשבון חדש
			 */
			create: () => LocalizedString
			/**
			 * העלת קובץ מאסטר
			 */
			upload: () => LocalizedString
			/**
			 * מחיקת חשבונות ידניים
			 */
			'delete': () => LocalizedString
		}
		columns: {
			/**
			 * שם חשבון
			 */
			account: () => LocalizedString
			/**
			 * סוג חשבון
			 */
			type: () => LocalizedString
			/**
			 * סוגי מידע
			 */
			dataTypes: () => LocalizedString
			/**
			 * סטטוס
			 */
			status: () => LocalizedString
			/**
			 * סוג מלאי
			 */
			inventoryType: () => LocalizedString
			/**
			 * כמות פעולות
			 */
			trxCount: () => LocalizedString
			/**
			 * פעולה ראשונה
			 */
			firstTrx: () => LocalizedString
			/**
			 * פעולה אחרונה
			 */
			lastTrx: () => LocalizedString
			/**
			 * תאריך סנכרון
			 */
			syncDate: () => LocalizedString
		}
		status: {
			/**
			 * חשבון ריק
			 */
			empty: () => LocalizedString
			/**
			 * בתהליך סינכרון
			 */
			syncing: () => LocalizedString
			/**
			 * סונכרן
			 */
			synced: () => LocalizedString
			/**
			 * חסר מידע
			 */
			'default': () => LocalizedString
		}
		context: {
			/**
			 * הגדרות מלאי
			 */
			inventory: () => LocalizedString
			/**
			 * צור חדש...
			 */
			createGroup: () => LocalizedString
			/**
			 * הצמד חשבון
			 */
			pin: () => LocalizedString
			/**
			 * הסר הצמדה לחשבון
			 */
			unpin: () => LocalizedString
		}
		messages: {
			/**
			 * החשבון נצמד בהצלחה
			 */
			pinned: () => LocalizedString
			/**
			 * החשבון הוסר מהצמדה בהצלחה
			 */
			unpinned: () => LocalizedString
			/**
			 * הגדרות מלאי עודכנו בהצלחה
			 */
			inventory: () => LocalizedString
			/**
			 * בקשה להעלאת קובץ מאסטר נשלחה בהצלחה
			 */
			master: () => LocalizedString
			/**
			 * בקשה למחיקת חשבונות ידניים נשלחה בהצלחה
			 */
			'delete': () => LocalizedString
		}
		confirm: {
			/**
			 * מחיקת חשבונות
			 */
			title: () => LocalizedString
			content: {
				/**
				 *  אתה בטוח שרוצה למחוק
				 */
				'0': () => LocalizedString
				/**
				 * חשבון אחד
				 */
				'1': () => LocalizedString
				/**
				 *  חשבונות
				 */
				'2': () => LocalizedString
				/**
				 * שים לב! כל הפעולות, הגדרות וקבצים ימחקו ללא אפשרות שחזור
				 */
				'3': () => LocalizedString
			}
		}
	}
	AccountDataTypes: {
		/**
		 * קבצים
		 */
		files: () => LocalizedString
		/**
		 * API
		 */
		api: () => LocalizedString
		/**
		 * תתי-חשבונות
		 */
		subaccounts: () => LocalizedString
		/**
		 * קובץ מאסטר
		 */
		master: () => LocalizedString
	}
	Sources: {
		buttons: {
			/**
			 * חשבון פעולות ידני
			 */
			manualAccount: () => LocalizedString
			/**
			 * חשבון Bloxtax
			 */
			bloxtaxAccount: () => LocalizedString
			/**
			 * חבילת ארנקים
			 */
			walletsBatch: () => LocalizedString
		}
		cards: {
			/**
			 * בורסה
			 */
			exchange: () => LocalizedString
			/**
			 * ארנק
			 */
			wallet: () => LocalizedString
		}
		form: {
			/**
			 * חשבון משנה
			 */
			subaccount: () => LocalizedString
			key: {
				/**
				 * API Key
				 */
				label: () => LocalizedString
				/**
				 * הכנס API Key
				 */
				placeholder: () => LocalizedString
			}
			secret: {
				/**
				 * API Secret
				 */
				label: () => LocalizedString
				/**
				 * הכנס API Secret
				 */
				placeholder: () => LocalizedString
			}
			passphrase: {
				/**
				 * Passphrase
				 */
				label: () => LocalizedString
				/**
				 * הכנס Passphrase
				 */
				placeholder: () => LocalizedString
			}
			address: {
				/**
				 * כתובת ארנק
				 */
				label: () => LocalizedString
				/**
				 * הכנס כתובת
				 */
				placeholder: () => LocalizedString
			}
			/**
			 * בדיקת ארנקים פעילים בכל רשת
			 */
			checkActiveWallets: () => LocalizedString
			fromDate: {
				/**
				 * תאריך תחילת פעילות
				 */
				label: () => LocalizedString
				/**
				 * בחר תאריך
				 */
				placeholder: () => LocalizedString
			}
			/**
			 * כולל חוזים עתידיים
			 */
			withFutures: () => LocalizedString
			ico: {
				amount: {
					/**
					 * כמות העברה
					 */
					label: () => LocalizedString
					/**
					 * הכנס כמות
					 */
					placeholder: () => LocalizedString
				}
				currency: {
					/**
					 * מטבע העברה
					 */
					label: () => LocalizedString
					/**
					 * הכנס מטבע
					 */
					placeholder: () => LocalizedString
				}
			}
			pool: {
				address: {
					/**
					 * LP טוקן
					 */
					label: () => LocalizedString
					/**
					 * הכנס כתובת
					 */
					placeholder: () => LocalizedString
				}
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			vault: {
				address: {
					/**
					 * חוזה חכם
					 */
					label: () => LocalizedString
					/**
					 * הכנס כתובת
					 */
					placeholder: () => LocalizedString
				}
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			loanfiat: {
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			loancrypto: {
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			lendfiat: {
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			lendcrypto: {
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			staking: {
				close_method: {
					/**
					 * איפוס יתרה - סיווג
					 */
					label: () => LocalizedString
					/**
					 * בחר סיווג
					 */
					placeholder: () => LocalizedString
				}
				close_date: {
					/**
					 * איפוס יתרה - תאריך
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
			}
			blackbox: {
				address: {
					/**
					 * חוזה חכם
					 */
					label: () => LocalizedString
					/**
					 * הכנס כתובת
					 */
					placeholder: () => LocalizedString
				}
			}
		}
	}
	SourceTrx: {
		columns: {
			/**
			 * חשבון
			 */
			account: () => LocalizedString
			/**
			 * סיווג
			 */
			method: () => LocalizedString
			/**
			 * תת-חשבון
			 */
			subAccount: () => LocalizedString
			/**
			 * תאריך
			 */
			date: () => LocalizedString
			/**
			 * קנייה
			 */
			buy: () => LocalizedString
			/**
			 * מכירה
			 */
			sell: () => LocalizedString
			/**
			 * עמלה
			 */
			fee: () => LocalizedString
			/**
			 * סכום
			 */
			amount: () => LocalizedString
			/**
			 * מטבע
			 */
			currency: () => LocalizedString
			/**
			 * טוקן
			 */
			token: () => LocalizedString
			/**
			 * מזהה (TxHash)
			 */
			idHash: () => LocalizedString
			/**
			 * סיווג Bitquery
			 */
			bitqueryMethod: () => LocalizedString
			/**
			 * חוזה חכם
			 */
			smartContract: () => LocalizedString
			/**
			 * שולח
			 */
			sender: () => LocalizedString
			/**
			 * מקבל
			 */
			receiver: () => LocalizedString
			/**
			 * מקור
			 */
			source: () => LocalizedString
			/**
			 * הערות
			 */
			comments: () => LocalizedString
			/**
			 * מזהה-BLX
			 */
			id: () => LocalizedString
		}
		context: {
			/**
			 * סיווגים
			 */
			methods: () => LocalizedString
			/**
			 * הסר סיווג
			 */
			mapRemove: () => LocalizedString
			/**
			 * נקה פעולות
			 */
			mapClear: () => LocalizedString
			/**
			 * הצג ב-
			 */
			scan: () => LocalizedString
			/**
			 * לכלול פעולות
			 */
			activateTrx: () => LocalizedString
			/**
			 * להיתעלם מהפעולות
			 */
			deactivateTrx: () => LocalizedString
		}
		errors: {
			/**
			 * חסרה קנייה או/ו קיימת מכירה
			 */
			'default-in-error': () => LocalizedString
			/**
			 * חסרה מכירה או/ו קיימת קנייה
			 */
			'default-out-error': () => LocalizedString
			/**
			 * חסרה קנייה
			 */
			'in-error': () => LocalizedString
			/**
			 * חסרה מכירה
			 */
			'out-error': () => LocalizedString
			/**
			 * חסרה קנייה או מכירה
			 */
			'default-double-error': () => LocalizedString
			/**
			 * חסרה קנייה ומכירה
			 */
			'raw-error': () => LocalizedString
			/**
			 * סוג פעולה לא ידוע
			 */
			'type-error': () => LocalizedString
			/**
			 * חסר חשבון
			 */
			'account-error': () => LocalizedString
			/**
			 * כמות פעולות לא מתאים לחיבור
			 */
			'merge-count-error': () => LocalizedString
			/**
			 * כמות פעולות לא מתאים להעברה
			 */
			'transfer-count-error': () => LocalizedString
			/**
			 * סוג פעולה לא מתאים לחיבור
			 */
			'merge-type-error': () => LocalizedString
			/**
			 * סוג פעולה לא מתאים להעברה
			 */
			'transfer-type-error': () => LocalizedString
			/**
			 * חסר תת-חשבון
			 */
			'subaccount-error': () => LocalizedString
		}
		filters: {
			/**
			 * תגים
			 */
			tags: () => LocalizedString
			showNotNormalized: {
				/**
				 * כולל לא מנורמלים
				 */
				include: () => LocalizedString
				/**
				 * ללא לא מנורמלים
				 */
				exclude: () => LocalizedString
				/**
				 * לא מנורמלים בלבד
				 */
				only: () => LocalizedString
			}
			showIgnored: {
				/**
				 * כולל להיתעלם
				 */
				include: () => LocalizedString
				/**
				 * ללא להיתעלם
				 */
				exclude: () => LocalizedString
				/**
				 * להיתעלם בלבד
				 */
				only: () => LocalizedString
			}
			showEmpty: {
				/**
				 * כולל חסר סיווג
				 */
				include: () => LocalizedString
				/**
				 * ללא חסר סיווג
				 */
				exclude: () => LocalizedString
				/**
				 * חסר סיווג בלבד
				 */
				only: () => LocalizedString
			}
			showManuals: {
				/**
				 * כולל פעולות ידניות
				 */
				include: () => LocalizedString
				/**
				 * ללא פעולות ידניות
				 */
				exclude: () => LocalizedString
				/**
				 * פעולות ידניות בלבד
				 */
				only: () => LocalizedString
			}
			showTransfers: {
				/**
				 * כולל העברות
				 */
				include: () => LocalizedString
				/**
				 * ללא העברות
				 */
				exclude: () => LocalizedString
				/**
				 * העברות בלבד
				 */
				only: () => LocalizedString
			}
			showNfts: {
				/**
				 * כולל NFT's
				 */
				include: () => LocalizedString
				/**
				 * ללא NFT's
				 */
				exclude: () => LocalizedString
				/**
				 * NFT's בלבד
				 */
				only: () => LocalizedString
			}
			/**
			 * הסתר תגים
			 */
			hideTags: () => LocalizedString
			/**
			 * מצב עבודה על DEFI
			 */
			showWalletsOnly: () => LocalizedString
		}
	}
	AgGrid: {
		contextMenu: {
			/**
			 * ייצא לאקסל
			 */
			exportToExcel: () => LocalizedString
			/**
			 * הוספה
			 */
			add: () => LocalizedString
			/**
			 * עריכה
			 */
			edit: () => LocalizedString
			/**
			 * מחיקה
			 */
			remove: () => LocalizedString
			importFromExcel: {
				/**
				 * ייבוא
				 */
				title: () => LocalizedString
				/**
				 * ייבא מאקסל
				 */
				'import': () => LocalizedString
				/**
				 * קובץ דוגמא
				 */
				example: () => LocalizedString
			}
			/**
			 * אפס סינון
			 */
			resetFilters: () => LocalizedString
			/**
			 * רענן נתונים
			 */
			refreshData: () => LocalizedString
			/**
			 * התאם עמודות לרוחב
			 */
			fitColumns: () => LocalizedString
			/**
			 * התאם עמודות
			 */
			autoSizeColumns: () => LocalizedString
			/**
			 * פתח ב
			 */
			openIn: () => LocalizedString
			/**
			 * העתק מזהה Bloxtax
			 */
			copyId: () => LocalizedString
		}
		'default': {
			/**
			 * חסר מידע
			 */
			empty: () => LocalizedString
		}
	}
	Components: {
		Upload: {
			/**
			 * שגיאה
			 */
			error: () => LocalizedString
			statuses: {
				/**
				 * העלאת קובץ
				 */
				uploading: () => LocalizedString
				/**
				 * הועלאה בהצלחה
				 */
				done: () => LocalizedString
				/**
				 * שגיאה בהעלאה
				 */
				error: () => LocalizedString
			}
		}
	}
	InventoryTypes: {
		/**
		 * אוטומטי
		 */
		auto: () => LocalizedString
		/**
		 * משותף
		 */
		shared: () => LocalizedString
		/**
		 * לא משותף
		 */
		self: () => LocalizedString
		/**
		 * קבוצתי
		 */
		group: () => LocalizedString
	}
	TransactionTypes: {
		/**
		 * רווח ריבית
		 */
		income_lending: () => LocalizedString
		/**
		 * דיבידנד
		 */
		income_dividend: () => LocalizedString
		/**
		 * רווח הון
		 */
		income_future: () => LocalizedString
		/**
		 * הכנסה נדחית
		 */
		income_deferred: () => LocalizedString
		/**
		 * הפסד הון
		 */
		lost_future: () => LocalizedString
		/**
		 * כריה
		 */
		mining: () => LocalizedString
		/**
		 * תקבול
		 */
		income: () => LocalizedString
		/**
		 * רכישה
		 */
		purchase: () => LocalizedString
		/**
		 * תשלום
		 */
		payment: () => LocalizedString
		/**
		 * מתנה
		 */
		gift: () => LocalizedString
		/**
		 * נתינת מתנה
		 */
		donate: () => LocalizedString
		/**
		 * אבד
		 */
		lost: () => LocalizedString
		/**
		 * המרה
		 */
		trade: () => LocalizedString
		/**
		 * שחלוף
		 */
		swap: () => LocalizedString
		/**
		 * משיכה לחשבון אחר
		 */
		transfer_out: () => LocalizedString
		/**
		 * הפקדה מחשבון אחר
		 */
		transfer_in: () => LocalizedString
		/**
		 * משיכה
		 */
		withdrawal: () => LocalizedString
		/**
		 * הפקדה
		 */
		deposit: () => LocalizedString
		/**
		 * סטייקינג
		 */
		staking: () => LocalizedString
		/**
		 * עמלה
		 */
		fee: () => LocalizedString
	}
	MapMethods: {
		/**
		 * רווח ריבית
		 */
		income_lending: () => LocalizedString
		/**
		 * דיבידנד
		 */
		income_dividend: () => LocalizedString
		/**
		 * רווח הון
		 */
		income_future: () => LocalizedString
		/**
		 * הכנסה נדחית
		 */
		income_deferred: () => LocalizedString
		/**
		 * הפסד הון
		 */
		lost_future: () => LocalizedString
		/**
		 * כריה
		 */
		mining: () => LocalizedString
		/**
		 * תקבול
		 */
		income: () => LocalizedString
		/**
		 * רכישה
		 */
		purchase: () => LocalizedString
		/**
		 * תשלום
		 */
		payment: () => LocalizedString
		/**
		 * מתנה
		 */
		gift: () => LocalizedString
		/**
		 * נתינת מתנה
		 */
		donate: () => LocalizedString
		/**
		 * אבד
		 */
		lost: () => LocalizedString
		/**
		 * המרה
		 */
		trade: () => LocalizedString
		/**
		 * שחלוף
		 */
		swap: () => LocalizedString
		/**
		 * גשר
		 */
		bridge: () => LocalizedString
		/**
		 * משיכה לחשבון אחר
		 */
		transfer_out: () => LocalizedString
		/**
		 * הפקדה מחשבון אחר
		 */
		transfer_in: () => LocalizedString
		/**
		 * משיכה
		 */
		withdrawal: () => LocalizedString
		/**
		 * הפקדה
		 */
		deposit: () => LocalizedString
		/**
		 * סטייקינג
		 */
		staking: () => LocalizedString
		/**
		 * עמלה
		 */
		fee: () => LocalizedString
		/**
		 * קבלת הלוואה
		 */
		loan: () => LocalizedString
		/**
		 * נתינת הלוואה
		 */
		lend: () => LocalizedString
		/**
		 * קופסה שחורה
		 */
		blackbox: () => LocalizedString
		/**
		 * כספת
		 */
		vault: () => LocalizedString
		/**
		 * ICO
		 */
		ico: () => LocalizedString
		/**
		 * Pool Out
		 */
		poolout: () => LocalizedString
		/**
		 * Pool In
		 */
		poolin: () => LocalizedString
		/**
		 * התעלם
		 */
		ignored: () => LocalizedString
		/**
		 * העברה ידועה
		 */
		transfer: () => LocalizedString
		/**
		 * העברה לא ידועה
		 */
		utransfer: () => LocalizedString
	}
	MapMethodsExt: {
		/**
		 * קנייה
		 */
		buy: () => LocalizedString
		/**
		 * מכירה
		 */
		sell: () => LocalizedString
	}
	MapMethodsAddon: {
		/**
		 * קבלת הלוואה בקריפטו
		 */
		loancrypto: () => LocalizedString
		/**
		 * נתינת הלוואה בקריפטו
		 */
		lendcrypto: () => LocalizedString
		/**
		 * קבלת הלוואה בפיאט
		 */
		loanfiat: () => LocalizedString
		/**
		 * נתינת הלוואה בפיאט
		 */
		lendfiat: () => LocalizedString
	}
	MapTypes: {
		/**
		 * אוטומטי
		 */
		auto: () => LocalizedString
		/**
		 * ידני
		 */
		manual: () => LocalizedString
		/**
		 * MapFile
		 */
		file: () => LocalizedString
		/**
		 * Defi algorytm
		 */
		defi: () => LocalizedString
	}
	SourceKind: {
		/**
		 * בורסה
		 */
		exchange: () => LocalizedString
		/**
		 * ארנק
		 */
		wallet: () => LocalizedString
		/**
		 * בלוקצ׳יין
		 */
		blockchain: () => LocalizedString
	}
	SourceType: {
		/**
		 * קובץ
		 */
		file: () => LocalizedString
		/**
		 * API
		 */
		api: () => LocalizedString
		/**
		 * ידני
		 */
		manual: () => LocalizedString
	}
	ExchangeRateSources: {
		/**
		 * CryptoCompare
		 */
		cc: () => LocalizedString
		/**
		 * CoinGeko
		 */
		cg: () => LocalizedString
		/**
		 * בנק ישראל
		 */
		boi: () => LocalizedString
		/**
		 * Fixer
		 */
		fixer: () => LocalizedString
		/**
		 * מנהל מערכת
		 */
		manual: () => LocalizedString
		/**
		 * קובץ
		 */
		file: () => LocalizedString
		/**
		 * חסר מידע
		 */
		unknown: () => LocalizedString
	}
	MadadRateSources: {
		/**
		 * הלשכה המרכזית לסטטיסטיקה
		 */
		cbs: () => LocalizedString
		/**
		 * מנהל מערכת
		 */
		manual: () => LocalizedString
		/**
		 * חסר מידע
		 */
		unknown: () => LocalizedString
	}
	General: {
		/**
		 * כן
		 */
		'true': () => LocalizedString
		/**
		 * לא
		 */
		'false': () => LocalizedString
		/**
		 * חיפוש...
		 */
		search: () => LocalizedString
	}
	TaskStatus: {
		/**
		 * ממתין לאישור
		 */
		pendingApproval: () => LocalizedString
		/**
		 * ממתין
		 */
		pending: () => LocalizedString
		/**
		 * מתחיל
		 */
		launch: () => LocalizedString
		/**
		 * בעבודה
		 */
		running: () => LocalizedString
		/**
		 * בוצע
		 */
		completed: () => LocalizedString
		/**
		 * נכשל
		 */
		failed: () => LocalizedString
		/**
		 * בוטל
		 */
		terminated: () => LocalizedString
	}
	TaskTypes: {
		/**
		 * עיבוד קובץ
		 */
		parser: () => LocalizedString
		/**
		 * נורמליזציה
		 */
		normalization: () => LocalizedString
		/**
		 * API
		 */
		api: () => LocalizedString
		/**
		 * טיימליין
		 */
		timeline: () => LocalizedString
		/**
		 * ייבוא שערי המרה
		 */
		importRates: () => LocalizedString
		/**
		 * דוחות
		 */
		report: () => LocalizedString
		/**
		 * העברות
		 */
		transfers: () => LocalizedString
		/**
		 * דוחות יומן
		 */
		journal: () => LocalizedString
		/**
		 * מחיקות
		 */
		deletion: () => LocalizedString
		/**
		 * מיגרציה
		 */
		migration: () => LocalizedString
		/**
		 * הכנסת נתונים
		 */
		insertData: () => LocalizedString
		/**
		 * השלמת נתונים
		 */
		completer: () => LocalizedString
		/**
		 * בדיקת ארנקים
		 */
		wallets: () => LocalizedString
		/**
		 * אלגוריתם DEFI
		 */
		defi: () => LocalizedString
		/**
		 * סטטיסטיקות
		 */
		stats: () => LocalizedString
		/**
		 * יתרות פתיחה
		 */
		openBalance: () => LocalizedString
		/**
		 * ייצאו/ייבוא
		 */
		'export': () => LocalizedString
		/**
		 * שמירת דוח משותף
		 */
		saving: () => LocalizedString
		/**
		 * ולידאציה
		 */
		validation: () => LocalizedString
	}
	WatchdogTypes: {
		/**
		 * הפעלת משימה
		 */
		start: () => LocalizedString
		/**
		 * הפסקת משימה
		 */
		stop: () => LocalizedString
		/**
		 * הפעלה מחדש (עם איפוס)
		 */
		restart: () => LocalizedString
		/**
		 * ביטול משימה
		 */
		terminate: () => LocalizedString
	}
	TaskRunTime: {
		/**
		 * פחות מדקה
		 */
		lessThanMinute: () => LocalizedString
		/**
		 * פחות משעה
		 */
		lessThanHour: () => LocalizedString
		/**
		 * פחות מיום
		 */
		lessThanDay: () => LocalizedString
		/**
		 * יותר מיום
		 */
		graterThanDay: () => LocalizedString
	}
	TransferTypes: {
		/**
		 * העברה מזוהה
		 */
		recognized: () => LocalizedString
		/**
		 * העברה חשודה
		 */
		suspicious: () => LocalizedString
		/**
		 * העברה מאושרת
		 */
		verified: () => LocalizedString
		/**
		 * העברה ידנית
		 */
		manual: () => LocalizedString
	}
	TransferContext: {
		/**
		 * אישור
		 */
		approve: () => LocalizedString
		/**
		 * דחייה
		 */
		decline: () => LocalizedString
		/**
		 * חיבור
		 */
		connect: () => LocalizedString
		/**
		 * הפרדה
		 */
		disconnect: () => LocalizedString
		/**
		 * פעולות
		 */
		operations: () => LocalizedString
	}
	AddressTypes: {
		/**
		 * חוזה חכם
		 */
		contract: () => LocalizedString
		/**
		 * ארנק
		 */
		wallet: () => LocalizedString
	}
	ReportTypes: {
		/**
		 * קלט
		 */
		input: () => LocalizedString
		/**
		 * קלט (ישן)
		 */
		'export': () => LocalizedString
		/**
		 * העברות
		 */
		transfers: () => LocalizedString
		/**
		 * טיימליין
		 */
		timeline: () => LocalizedString
		/**
		 * פעולות
		 */
		transactions: () => LocalizedString
		/**
		 * רווח והפסד
		 */
		gainloss: () => LocalizedString
		/**
		 * יתרות
		 */
		balance: () => LocalizedString
		/**
		 * יתרות (מורחב)
		 */
		balanceExtended: () => LocalizedString
		/**
		 * חסרים
		 */
		missings: () => LocalizedString
		/**
		 * פיאט
		 */
		fiat: () => LocalizedString
		/**
		 * טופס 1399
		 */
		f1399: () => LocalizedString
		/**
		 * פקודות יומן
		 */
		je: () => LocalizedString
		/**
		 * דוח סיכום
		 */
		summary: () => LocalizedString
	}
	RequestStatus: {
		/**
		 * דו״ח בבדיקה
		 */
		pending: () => LocalizedString
		/**
		 * ממתין לתשלום
		 */
		payment: () => LocalizedString
		/**
		 * אין אירועי מס
		 */
		noTax: () => LocalizedString
		/**
		 * נדרש מידע נוסף
		 */
		rejected: () => LocalizedString
		/**
		 * הסתיים
		 */
		completed: () => LocalizedString
		/**
		 * לא הופק
		 */
		unknown: () => LocalizedString
	}
	PaymentType: {
		/**
		 * אוטומטי
		 */
		auto: () => LocalizedString
		/**
		 * ידני
		 */
		manual: () => LocalizedString
		/**
		 * מקדמה
		 */
		pre: () => LocalizedString
	}
	CoaTypes: {
		/**
		 * הון עצמי
		 */
		capital: () => LocalizedString
		/**
		 * פעילות עסקית
		 */
		businessActivity: () => LocalizedString
		/**
		 * רווח והפסד
		 */
		gainLoss: () => LocalizedString
		/**
		 * הוצאות מימון
		 */
		financeActivity: () => LocalizedString
		/**
		 * נכסים
		 */
		assets: () => LocalizedString
		/**
		 * תשלומים
		 */
		payable: () => LocalizedString
		/**
		 * תקבולים
		 */
		receivable: () => LocalizedString
		/**
		 * התחייבויות
		 */
		liabilities: () => LocalizedString
	}
	CoaSettings: {
		/**
		 * חשבונות
		 */
		accounts: () => LocalizedString
		/**
		 * הגדרות
		 */
		options: () => LocalizedString
	}
	AccountTypes: {
		/**
		 * חשבון תשלומים
		 */
		payable: () => LocalizedString
		/**
		 * חשבון תקבולים
		 */
		receivable: () => LocalizedString
		/**
		 * חשבון הון עצמי
		 */
		capital: () => LocalizedString
		/**
		 * חשבון נכסים
		 */
		assets: () => LocalizedString
		/**
		 * חשבון התחייבויות
		 */
		liabilities: () => LocalizedString
	}
	Roles: {
		/**
		 * מנהל מערכת
		 */
		'super-admin': () => LocalizedString
		/**
		 * צוות Bloxtax
		 */
		admin: () => LocalizedString
		/**
		 * בעל ארגון
		 */
		'org-owner': () => LocalizedString
		/**
		 * שותף ארגון
		 */
		'org-partner': () => LocalizedString
		/**
		 * רואה חשבון
		 */
		cpa: () => LocalizedString
		/**
		 * רואה חשבון ארגון
		 */
		'org-cpa': () => LocalizedString
	}
	Permissions: {
		/**
		 * חשבונות
		 */
		accounts: () => LocalizedString
		/**
		 * פעולות
		 */
		transactions: () => LocalizedString
		/**
		 * יתרות וחוסרים
		 */
		balances: () => LocalizedString
		/**
		 * דוחות
		 */
		reports: () => LocalizedString
		/**
		 * הגדרות ארגון
		 */
		settings: () => LocalizedString
		categories: {
			/**
			 * חשבונות
			 */
			accounts: () => LocalizedString
			/**
			 * שדות API
			 */
			api_fields: () => LocalizedString
			/**
			 * יתרות וחוסרים, טיימליין
			 */
			balances: () => LocalizedString
			/**
			 * עדכוני מערכת
			 */
			changelog: () => LocalizedString
			/**
			 * אישורי יתרות
			 */
			close_balance: () => LocalizedString
			/**
			 * מטבעות קריפטו
			 */
			coins: () => LocalizedString
			/**
			 * סביבות מערכת
			 */
			environment: () => LocalizedString
			/**
			 * שערי המרה
			 */
			exchange_rates: () => LocalizedString
			/**
			 * מטבעות פיאט
			 */
			fiats: () => LocalizedString
			/**
			 * קבצים
			 */
			files: () => LocalizedString
			/**
			 * Freshdesk
			 */
			freshdesk: () => LocalizedString
			/**
			 * Global Map, Bitquery
			 */
			global_map: () => LocalizedString
			/**
			 * פקודות יומן
			 */
			journal_entries: () => LocalizedString
			/**
			 * Legacy
			 */
			legacy: () => LocalizedString
			/**
			 * שערי מדד
			 */
			madads: () => LocalizedString
			/**
			 * קבצי Map
			 */
			map_files: () => LocalizedString
			/**
			 * מיגראציות
			 */
			migration: () => LocalizedString
			/**
			 * רשתות
			 */
			networks: () => LocalizedString
			/**
			 * הודעות
			 */
			notifications: () => LocalizedString
			/**
			 * יתרות פתיחה
			 */
			open_balance: () => LocalizedString
			/**
			 * תפעול
			 */
			operations: () => LocalizedString
			/**
			 * ארגונים
			 */
			organizations: () => LocalizedString
			/**
			 * דפים/מסכים
			 */
			page: () => LocalizedString
			/**
			 * פרסרים
			 */
			parsers: () => LocalizedString
			/**
			 * Pipedrive
			 */
			pipedrive: () => LocalizedString
			/**
			 * דוחות/בקשות דוח
			 */
			reports: () => LocalizedString
			/**
			 * מלאים
			 */
			shared_inventory: () => LocalizedString
			/**
			 * מקורות מידע
			 */
			sources: () => LocalizedString
			/**
			 * פעולות גולמי
			 */
			source_trx: () => LocalizedString
			/**
			 * פעולות עם שגיות
			 */
			source_trx_drafts: () => LocalizedString
			/**
			 * פעולות ידניות
			 */
			source_trx_manual: () => LocalizedString
			/**
			 * מערכת
			 */
			system: () => LocalizedString
			/**
			 * תגים
			 */
			tags: () => LocalizedString
			/**
			 * משימות
			 */
			tasks: () => LocalizedString
			/**
			 * פעולות מנורמלות
			 */
			transactions: () => LocalizedString
			/**
			 * העברות
			 */
			transfers: () => LocalizedString
			/**
			 * סיווגים
			 */
			trx_map: () => LocalizedString
			/**
			 * משתמשים
			 */
			users: () => LocalizedString
			/**
			 * ולידאציות
			 */
			validations: () => LocalizedString
			/**
			 * Wizard
			 */
			wizard: () => LocalizedString
		}
	}
	SubaccountTypes: {
		/**
		 * חשבון-ICO
		 */
		ico: () => LocalizedString
		/**
		 * חשבון-Pool
		 */
		pool: () => LocalizedString
		/**
		 * חשבון כספת
		 */
		vault: () => LocalizedString
		/**
		 * חשבון קופסה שחורה
		 */
		blackbox: () => LocalizedString
		/**
		 * חשבון נתינת הלוואה בקריפטו
		 */
		lendcrypto: () => LocalizedString
		/**
		 * חשבון קבלת הלוואה בקריפטו
		 */
		loancrypto: () => LocalizedString
		/**
		 * חשבון נתינת הלוואה בפיאט
		 */
		lendfiat: () => LocalizedString
		/**
		 * חשבון קבלת הלוואה בפיאט
		 */
		loanfiat: () => LocalizedString
		/**
		 * יתרת פתיחה
		 */
		openBalance: () => LocalizedString
		/**
		 * אישור יתרות
		 */
		closeBalance: () => LocalizedString
		/**
		 * חשבון סטייקינג
		 */
		staking: () => LocalizedString
		/**
		 * תת-חשבון
		 */
		exchange: () => LocalizedString
		/**
		 * פעולות ידניות
		 */
		manual: () => LocalizedString
		/**
		 * הפרדת מלאים
		 */
		separation: () => LocalizedString
	}
	OpenBalanceTypes: {
		/**
		 * מיגראציה
		 */
		migration: () => LocalizedString
		/**
		 * הקפאת דוח
		 */
		report: () => LocalizedString
		/**
		 * מנהל מערכת
		 */
		manual: () => LocalizedString
	}
	OrganizationTypes: {
		/**
		 * פרטי
		 */
		basic: () => LocalizedString
		/**
		 * עסקי
		 */
		commercial: () => LocalizedString
	}
	UnsupportedTypes: {
		/**
		 * קובץ
		 */
		file: () => LocalizedString
		/**
		 * ארנק
		 */
		wallet: () => LocalizedString
	}
	UnsupportedsStatus: {
		/**
		 * לא קיים
		 */
		empty: () => LocalizedString
		/**
		 * טופל
		 */
		done: () => LocalizedString
		/**
		 * לא טופל
		 */
		'not-done': () => LocalizedString
	}
	PaymentStatus: {
		/**
		 * ממתין לתשלום
		 */
		pending: () => LocalizedString
		/**
		 * תשלומים
		 */
		payments: () => LocalizedString
		/**
		 * שולם
		 */
		completed: () => LocalizedString
		/**
		 * בוטל
		 */
		canceled: () => LocalizedString
		/**
		 * מומש
		 */
		applied: () => LocalizedString
	}
	PaymentItemTypes: {
		/**
		 * דוחות קריפטו
		 */
		reports: () => LocalizedString
		/**
		 * הגשות רואה חשבון
		 */
		submissions: () => LocalizedString
		/**
		 * דיווח מיקדמי
		 */
		pre_submission: () => LocalizedString
		/**
		 * סגירת תיק
		 */
		close_tax_file: () => LocalizedString
		/**
		 * הצהרת הון
		 */
		asset_declaration: () => LocalizedString
		/**
		 * ייעוץ
		 */
		consulting: () => LocalizedString
		/**
		 * נתיב הכסף
		 */
		money_trail: () => LocalizedString
		/**
		 * מקדמה
		 */
		prepayment: () => LocalizedString
		/**
		 * הנחה
		 */
		discount: () => LocalizedString
		/**
		 * מע״מ
		 */
		vat: () => LocalizedString
	}
	Errors: {
		'default': {
			/**
			 * שגיאה בעת ביצוע הפעולה
			 */
			message: () => LocalizedString
			/**
			 * אנא נסה שוב מאוחר יותר
			 */
			description: () => LocalizedString
		}
	}
	Messages: {
		/**
		 * בחר לפחות שורה אחד
		 */
		chooseOne: () => LocalizedString
	}
	Validations: {
		/**
		 * השדה הינו חובה
		 */
		isRequired: () => LocalizedString
		/**
		 * אימות סיסמות לא הושלם
		 */
		compare: () => LocalizedString
		/**
		 * השדה חייב להיות מספר חיובי
		 */
		isPositiveNumber: () => LocalizedString
		/**
		 * השדה לא יכול להיות שווה לאפס
		 */
		notZeroNumber: () => LocalizedString
		/**
		 * המספר חייב להיות קטן מ-{less}
		 */
		isLessThen: (arg: { less: unknown }) => LocalizedString
		/**
		 * השדה חייב להכיל אותיות בלבד
		 */
		isValidText: () => LocalizedString
		/**
		 * השדה חייב להכיל אותיות באנגלית או מספרים בלבד
		 */
		isValidCurrency: () => LocalizedString
		/**
		 * השדה חייב להיות כתובת אימייל תקין
		 */
		isValidEmail: () => LocalizedString
		/**
		 * השדה חייב להיות מספר טלפון תקין
		 */
		isValidPhone: () => LocalizedString
		/**
		 * השדה חייב להיות כתובת {name} תקינה
		 */
		isValidAddress: (arg: { name: unknown }) => LocalizedString
		isValidApi: {
			/**
			 * השדה חייב להיות מפתח {name} תקין
			 */
			invalid: (arg: { name: unknown }) => LocalizedString
			/**
			 * חסרים הרשאות מתאימות למפתח זה
			 */
			permissions: () => LocalizedString
			/**
			 * חסרת הרשאת Futures למפתח זה, יש לאפשר את כל ההרשאות בהתאם למדריך
			 */
			'permissions-futures': () => LocalizedString
			/**
			 * לא זוהה סוג API - פנה לתמיכה
			 */
			unknown: () => LocalizedString
		}
		/**
		 * הארנק כבר קיים
		 */
		isWalletExists: () => LocalizedString
		/**
		 * API זה כבר קיים
		 */
		isApiExists: () => LocalizedString
		/**
		 * השדה צבע הינו חובה
		 */
		isRequiredTag: () => LocalizedString
		/**
		 * צבע תג כבר קיים
		 */
		isTagExists: () => LocalizedString
		/**
		 * השדה לא יכול להכיל רווחים
		 */
		isNoSpaces: () => LocalizedString
		/**
		 * מטבע ראשי זה כבר קיים
		 */
		isMainCoinExists: () => LocalizedString
		file: {
			/**
			 * שים לב, הקובץ שהעלת ריק - לא נקלטו פעולות מהקובץ
			 */
			empty: () => LocalizedString
			/**
			 * מבנה הקובץ לא תקין, יש לעקוב אחרי ההנחיות, ולהעלות את הקובץ מחדש
			 */
			format: () => LocalizedString
			/**
			 * קובץ פגום
			 */
			corrupted: () => LocalizedString
		}
		signup: {
			/**
			 * {field} זה כבר נמצא במערכת
			 */
			form_identifier_exists: (arg: { field: unknown }) => LocalizedString
			/**
			 * הסיסמה שלך חייבת להכיל 8 תווים או יותר
			 */
			form_password_length_too_short: () => LocalizedString
			/**
			 * הסיסמה שלך אינה מספיק חזקה
			 */
			form_password_not_strong_enough: () => LocalizedString
			/**
			 * הסיסמה הזו נמצאה כחלק מהפרטים שנחשפו בהפרת נתונים ולא ניתן להשתמש בה
			 */
			form_password_pwned: () => LocalizedString
			/**
			 * קוד אימות שלך אינו תקין
			 */
			form_code_incorrect: () => LocalizedString
		}
	}
	TimelineTypes: {
		/**
		 * המרה
		 */
		TRADE: () => LocalizedString
		/**
		 * הפקדה
		 */
		DEPOSIT: () => LocalizedString
		/**
		 * משיכה
		 */
		WITHDRAWAL: () => LocalizedString
		/**
		 * הפקדה מחשבון אחר
		 */
		TRANSFER_IN: () => LocalizedString
		/**
		 * משיכה לחשבון אחר
		 */
		TRANSFER_OUT: () => LocalizedString
	}
	TimelineSuspisious: {
		/**
		 * ראינו שיש הפקדה ראשונה ללא תיעוד של רכישה. יש להזין מאיפה הגיעו המטבעות מלכתחילה
		 */
		first_deposit: () => LocalizedString
		/**
		 * זיהינו הפקדה שגדולה יותר מהיתרה, כנראה חסר תיעוד של רכישה
		 */
		grater_than_inventoryPositive: () => LocalizedString
		/**
		 * הפעולה הראשונה בחשבון היא פעולת מכירה, חסר תיעוד של רכישת המטבעות
		 */
		first_sell: () => LocalizedString
		/**
		 * יש חוסר – מכירה אשר יותר גדולה מהיתרה שלך בזמן הנתון
		 */
		missing: () => LocalizedString
	}
	Support: {
		/**
		 * שחזור משתמש מהמערכת הישנה
		 */
		'0': () => LocalizedString
		/**
		 * שגיאה בהעלאת נתונים
		 */
		'1': () => LocalizedString
		/**
		 * תקלת מערכת
		 */
		'2': () => LocalizedString
		/**
		 * יתרות שגויות
		 */
		'3': () => LocalizedString
		/**
		 * הסבר על הדוחות
		 */
		'4': () => LocalizedString
		/**
		 * הסבר על המערכת
		 */
		'5': () => LocalizedString
		/**
		 * הצעות לשיפור
		 */
		'6': () => LocalizedString
	}
	RequestSummary: {
		values: {
			/**
			 * להיתעלם
			 */
			ignore: () => LocalizedString
			/**
			 * לכלול
			 */
			include: () => LocalizedString
			/**
			 * שווה אפס
			 */
			'as-zero': () => LocalizedString
			/**
			 * שווי שוק
			 */
			'as-value': () => LocalizedString
			/**
			 * כן
			 */
			'true': () => LocalizedString
			/**
			 * לא
			 */
			'false': () => LocalizedString
		}
		metadata: {
			/**
			 * משתמש
			 */
			user: () => LocalizedString
			/**
			 * ארגון
			 */
			organization: () => LocalizedString
			/**
			 * תאריך
			 */
			date: () => LocalizedString
			/**
			 * מטבע משתמש
			 */
			user_currency: () => LocalizedString
			/**
			 * אזור זמן
			 */
			timezone: () => LocalizedString
			/**
			 * Cutoff
			 */
			cutoff: () => LocalizedString
			/**
			 * יתרות פתיחה
			 */
			openBalance: () => LocalizedString
			/**
			 * אישור יתרות
			 */
			closeBalance: () => LocalizedString
			/**
			 * Fair value (end of year)
			 */
			fairValue: () => LocalizedString
			/**
			 * Custom Fair value date
			 */
			customFairValue: () => LocalizedString
			/**
			 * סוג חישוב
			 */
			calculation: () => LocalizedString
			/**
			 * סוג חישוב עלות חוסרים
			 */
			missing_policy: () => LocalizedString
			/**
			 * התייחסות להפקדות/משיכות
			 */
			deposit_withdrawals_policy: () => LocalizedString
			/**
			 * יתרות פיאט
			 */
			fiat_policy: () => LocalizedString
			/**
			 * התייחסות למלאים
			 */
			inventory_policy: () => LocalizedString
			/**
			 * התייחסות למזהה מטבעות
			 */
			coinInventory_policy: () => LocalizedString
			/**
			 * דוחות
			 */
			reports: () => LocalizedString
			/**
			 * חשבונות
			 */
			accounts: () => LocalizedString
			/**
			 * PDF
			 */
			pdf: () => LocalizedString
			/**
			 * שגיאות בדוח
			 */
			found_errors: () => LocalizedString
			/**
			 * עלות יתרות פתיחה
			 */
			open_balance_trx: () => LocalizedString
			/**
			 * הפרדות מלאים
			 */
			inventory_separation: () => LocalizedString
			/**
			 * העברות לא מזוות
			 */
			unrecognized_transfers: () => LocalizedString
		}
		/**
		 * כמות פעולות גולמי
		 */
		source_transactions_count: () => LocalizedString
		/**
		 * כמות פעולות
		 */
		transactions_count: () => LocalizedString
		/**
		 * כמות פעולות בלהיתעלם
		 */
		ignored_transactions_count: () => LocalizedString
		/**
		 * כמות אירועי המס
		 */
		tax_events_count: () => LocalizedString
		/**
		 * כמות אירועי סטייקינג/כרייה
		 */
		stax_events_count: () => LocalizedString
		/**
		 * נפח מסחר
		 */
		trading_volume: () => LocalizedString
		/**
		 * נפח עמלות
		 */
		fee_volume: () => LocalizedString
		/**
		 * שינוי בפיאט
		 */
		fiat_change: () => LocalizedString
		/**
		 * רווח והפסד
		 */
		gain_loss: () => LocalizedString
		/**
		 * הכנסות
		 */
		incomes: () => LocalizedString
		/**
		 * כריה
		 */
		mining: () => LocalizedString
		/**
		 * סטייקינג
		 */
		staking: () => LocalizedString
		/**
		 * רווח ריבית (פיאט)
		 */
		income_lending_fiats: () => LocalizedString
		/**
		 * חוסרים
		 */
		missing: () => LocalizedString
		/**
		 * חוסרים שווה 0
		 */
		zeromissing: () => LocalizedString
		/**
		 * סגירות פערים
		 */
		balance_adjustments: () => LocalizedString
		/**
		 * יתרות סגירה
		 */
		closing_balance: () => LocalizedString
		/**
		 * יתרות סגירה (שווי)
		 */
		closing_balance_values: () => LocalizedString
	}
	LogLevel: {
		/**
		 * מידע
		 */
		info: () => LocalizedString
		/**
		 * אזהרה
		 */
		warning: () => LocalizedString
		/**
		 * שגיאה
		 */
		error: () => LocalizedString
	}
	AnnouncementType: {
		/**
		 * כולם
		 */
		all: () => LocalizedString
		/**
		 * ארגון
		 */
		organization: () => LocalizedString
		/**
		 * משתמש
		 */
		user: () => LocalizedString
	}
	Api: {
		Functions: {
			form: {
				downloadId: {
					/**
					 * Download ID
					 */
					label: () => LocalizedString
					/**
					 * הכנס Download ID
					 */
					placeholder: () => LocalizedString
				}
				symbol: {
					/**
					 * Symbol
					 */
					label: () => LocalizedString
					/**
					 * הכנס Symbol
					 */
					placeholder: () => LocalizedString
				}
				orderId: {
					/**
					 * Order ID
					 */
					label: () => LocalizedString
					/**
					 * הכנס Order ID
					 */
					placeholder: () => LocalizedString
				}
				startTime: {
					/**
					 * תאריך תחילה
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
				endTime: {
					/**
					 * תאריך סיום
					 */
					label: () => LocalizedString
					/**
					 * בחר תאריך
					 */
					placeholder: () => LocalizedString
				}
				page: {
					/**
					 * מספר דף
					 */
					label: () => LocalizedString
					/**
					 * הכנס מספר דף
					 */
					placeholder: () => LocalizedString
				}
			}
		}
	}
	ImportTaskLogs: {
		/**
		 * בתהליך הכנה
		 */
		pending: () => LocalizedString
		/**
		 * בתהליך ייבוא
		 */
		importing: () => LocalizedString
		/**
		 * מייבא מ-cloudwatch
		 */
		imported: () => LocalizedString
	}
	Issues: {
		'ico:parameters': {
			/**
			 * Missing ICO account parameters
			 */
			short: () => LocalizedString
			/**
			 * Missing ICO account parameters
			 */
			full: () => LocalizedString
		}
		'api:parameters:permissions': {
			/**
			 * מפתח API אינו תקין
			 */
			short: () => LocalizedString
			/**
			 * לא הצלחנו להתחבר ל-API. זו בדרך כלל בעיה של הרשאות או שה-API כבר לא פעיל. אנא צור API חדש והעלה אותו מחדש למערכת
			 */
			full: () => LocalizedString
		}
		'api:data:binance-spot': {
			/**
			 * חסר קובץ Binance Trades
			 */
			short: () => LocalizedString
			/**
			 * נצאה בקשת API עבור Binance Spot Trades מעל שנתיים אחורה. יש להשתמש בקובץ Binance Trades במקום
			 */
			full: () => LocalizedString
		}
		'parser:data:date': {
			/**
			 * נמצאו תאריכים לא תקין בקובץ, יש להעלות את קובץ חדש
			 */
			short: () => LocalizedString
			/**
			 * נמצאו תאריכים לא תקינים בקובץ, זה קורה בדרך כלל לאחר פתיחה של הקובץ במחשב. יש להוריד את הקובץ מחדש מהמקור הרלוונטי ולהעלות אותו למערכת לפני פתיחה שלו במחשב
			 */
			full: () => LocalizedString
		}
		'api:unknown': {
			/**
			 * שגיאה - יש לברר במשימה
			 */
			short: () => LocalizedString
			/**
			 * בבקשה אל תבצע שינויים נוספים - התקלה עברה לצוות Bloxtax ובינתיים ניתן להמשיך לעבוד במערכת כרגיל
			 */
			full: () => LocalizedString
		}
		'parser:unknown': {
			/**
			 * שגיאה - יש לברר במשימה
			 */
			short: () => LocalizedString
			/**
			 * בבקשה אל תבצע שינויים נוספים - התקלה עברה לצוות Bloxtax ובינתיים ניתן להמשיך לעבוד במערכת כרגיל
			 */
			full: () => LocalizedString
		}
		'insertData:unknown': {
			/**
			 * שגיאה - יש לברר במשימה
			 */
			short: () => LocalizedString
			/**
			 * בבקשה אל תבצע שינויים נוספים - התקלה עברה לצוות Bloxtax ובינתיים ניתן להמשיך לעבוד במערכת כרגיל
			 */
			full: () => LocalizedString
		}
		/**
		 * שגיאה - יש לברר במשימה
		 */
		'task:unknown': () => LocalizedString
	}
}

export type Formatters = {}
